import * as stylex from "@stylexjs/stylex";

import { colors, radius } from "@/registry/bases/stylex/lib/tokens.stylex";

export const styles = stylex.create({
  actions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    position: "relative",
    zIndex: 20,
  },
  content: { flex: 1, lineHeight: 1.25, maxWidth: "100%", minWidth: 0 },
  description: {
    color: colors.mutedForeground,
    display: "block",
    fontSize: "0.75rem",
    marginTop: "0.125rem",
    maxWidth: "100%",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  error: {
    borderColor: `color-mix(in oklab, ${colors.destructive} 30%, transparent)`,
  },
  group: {
    display: "flex",
    gap: "0.75rem",
    minWidth: 0,
    overflowX: "auto",
    overscrollBehaviorInline: "contain",
    paddingBlock: "0.25rem",
    scrollSnapType: "x mandatory",
  },
  horizontal: { alignItems: "center", minWidth: "10rem" },
  idle: { borderStyle: "dashed" },
  media: {
    alignItems: "center",
    aspectRatio: "1",
    backgroundColor: colors.muted,
    borderRadius: radius.xl,
    color: colors.foreground,
    display: "flex",
    flexShrink: 0,
    justifyContent: "center",
    overflow: "hidden",
    width: "2.5rem",
  },
  mediaImage: { opacity: 0.8 },
  root: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: "1.5rem",
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.cardForeground,
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    maxWidth: "100%",
    minWidth: 0,
    position: "relative",
    transition: "color 150ms, background-color 150ms, border-color 150ms",
    width: "fit-content",
  },
  sizeDefault: { fontSize: "0.875rem", gap: "0.5rem", padding: "0.5rem" },
  sizeSm: { fontSize: "0.75rem", gap: "0.625rem", padding: "0.375rem" },
  sizeXs: {
    borderRadius: "1rem",
    fontSize: "0.75rem",
    gap: "0.375rem",
    padding: "0.25rem",
  },
  title: {
    display: "block",
    fontWeight: 500,
    maxWidth: "100%",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  trigger: { inset: 0, outline: "none", position: "absolute", zIndex: 10 },
  vertical: { flexDirection: "column", width: "6rem" },
});
