import * as stylex from "@stylexjs/stylex";

import { colors, radius } from "../tokens.stylex";

export const styles = stylex.create({
  icon: { height: "1rem", width: "1rem" },
  indicatorWrap: {
    alignItems: "center",
    display: "flex",
    height: "0.875rem",
    justifyContent: "center",
    left: "0.5rem",
    pointerEvents: "none",
    position: "absolute",
    width: "0.875rem",
  },
  item: {
    alignItems: "center",
    borderRadius: "0.125rem",
    cursor: "default",
    display: "flex",
    fontSize: "0.875rem",
    gap: "0.5rem",
    outline: "none",
    paddingBottom: "0.375rem",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    paddingTop: "0.375rem",
    position: "relative",
    transition: "background-color 0.1s ease, color 0.1s ease",
    userSelect: "none",
  },
  itemDestructive: { color: colors.destructive },
  itemDestructiveHighlighted: {
    backgroundColor: `color-mix(in oklab, ${colors.destructive} 10%, transparent)`,
    color: colors.destructive,
  },
  itemDisabled: { opacity: 0.5, pointerEvents: "none" },
  itemHighlighted: {
    backgroundColor: colors.accent,
    color: colors.accentForeground,
  },
  itemIndented: { paddingLeft: "2rem" },
  itemInset: { paddingLeft: "2rem" },
  label: {
    color: colors.foreground,
    fontSize: "0.875rem",
    fontWeight: 600,
    paddingBottom: "0.375rem",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    paddingTop: "0.375rem",
  },
  labelInset: { paddingLeft: "2rem" },
  popup: {
    backgroundColor: colors.popover,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow:
      "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
    color: colors.popoverForeground,
    minWidth: "8rem",
    opacity: 1,
    outline: "none",
    overflow: "hidden",
    padding: "0.25rem",
    transform: "scale(1)",
    transformOrigin: "var(--transform-origin)",
    transition: "opacity 0.15s ease-in-out, transform 0.15s ease-in-out",
    zIndex: 50,
  },
  popupHidden: { opacity: 0, transform: "scale(0.95)" },
  separator: {
    backgroundColor: colors.border,
    height: "1px",
    marginBottom: "0.25rem",
    marginLeft: "-0.25rem",
    marginRight: "-0.25rem",
    marginTop: "0.25rem",
  },
  shortcut: {
    color: colors.mutedForeground,
    fontSize: "0.75rem",
    letterSpacing: "0.05em",
    marginLeft: "auto",
    opacity: 0.6,
  },
});
