import * as stylex from "@stylexjs/stylex";

import { colors, radius } from "../tokens.stylex";

export const s = stylex.create({
  container: {
    bottom: 0,
    display: "flex",
    height: "100svh",
    position: "fixed",
    top: 0,
    transition:
      "left 0.2s ease-in-out, right 0.2s ease-in-out, width 0.2s ease-in-out",
    zIndex: 10,
  },
  content: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: "0.5rem",
    minHeight: 0,
    overflow: "auto",
  },
  footer: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    padding: "0.5rem",
  },
  gap: {
    backgroundColor: "transparent",
    position: "relative",
    transition: "width 0.2s ease-in-out",
  },
  group: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    padding: "0.5rem",
    position: "relative",
    width: "100%",
  },
  groupContent: {
    fontSize: "0.875rem",
    width: "100%",
  },
  groupLabel: {
    alignItems: "center",
    borderRadius: radius.md,
    color: `color-mix(in oklab, ${colors.sidebarForeground} 70%, transparent)`,
    display: "flex",
    flexShrink: 0,
    fontSize: "0.75rem",
    fontWeight: 500,
    height: "2rem",
    outline: "none",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    padding: "0.5rem",
  },
  inner: {
    backgroundColor: colors.sidebar,
    color: colors.sidebarForeground,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    width: "100%",
  },
  inset: {
    backgroundColor: colors.background,
    display: "flex",
    flex: 1,
    flexDirection: "column",
    position: "relative",
    width: "100%",
  },
  menu: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    listStyle: "none",
    margin: 0,
    minWidth: 0,
    padding: 0,
    width: "100%",
  },
  menuAction: {
    alignItems: "center",
    aspectRatio: "1",
    backgroundColor: { ":hover": colors.sidebarAccent, default: "transparent" },
    borderRadius: radius.md,
    borderWidth: 0,
    color: colors.sidebarForeground,
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    outline: "none",
    padding: 0,
    position: "absolute",
    right: "0.25rem",
    top: "0.375rem",
    width: "1.25rem",
  },
  menuBadge: {
    alignItems: "center",
    borderRadius: radius.md,
    color: colors.sidebarForeground,
    display: "flex",
    fontSize: "0.75rem",
    fontVariantNumeric: "tabular-nums",
    fontWeight: 500,
    height: "1.25rem",
    justifyContent: "center",
    minWidth: "1.25rem",
    paddingLeft: "0.25rem",
    paddingRight: "0.25rem",
    pointerEvents: "none",
    position: "absolute",
    right: "0.25rem",
    top: "0.375rem",
    userSelect: "none",
  },
  menuButton: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.sidebarAccent, default: "transparent" },
    borderRadius: radius.md,
    borderWidth: 0,
    color: {
      ":hover": colors.sidebarAccentForeground,
      default: colors.sidebarForeground,
    },
    cursor: "pointer",
    display: "flex",
    fontSize: "0.875rem",
    fontWeight: 400,
    gap: "0.5rem",
    outline: "none",
    overflow: "hidden",
    padding: "0.5rem",
    textAlign: "left",
    transition: "background-color 0.1s ease, color 0.1s ease",
    width: "100%",
  },
  menuButtonActive: {
    backgroundColor: colors.sidebarAccent,
    color: colors.sidebarAccentForeground,
    fontWeight: 500,
  },
  menuButtonLg: { height: "3rem" },
  menuButtonSm: { fontSize: "0.75rem", height: "1.75rem" },
  menuItem: {
    position: "relative",
  },
  menuSkeleton: {
    alignItems: "center",
    borderRadius: radius.md,
    display: "flex",
    gap: "0.5rem",
    height: "2rem",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
  },
  menuSub: {
    borderLeftColor: colors.sidebarBorder,
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    listStyle: "none",
    marginLeft: "0.875rem",
    minWidth: 0,
    paddingBottom: "0.125rem",
    paddingLeft: "0.625rem",
    paddingTop: "0.125rem",
  },
  menuSubButton: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.sidebarAccent, default: "transparent" },
    borderRadius: radius.md,
    color: {
      ":hover": colors.sidebarAccentForeground,
      default: colors.sidebarForeground,
    },
    cursor: "pointer",
    display: "flex",
    gap: "0.5rem",
    height: "1.75rem",
    minWidth: 0,
    outline: "none",
    overflow: "hidden",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    textDecorationLine: "none",
    transition: "background-color 0.1s ease, color 0.1s ease",
  },
  menuSubButtonActive: {
    backgroundColor: colors.sidebarAccent,
    color: colors.sidebarAccentForeground,
  },
  menuSubItem: {
    position: "relative",
  },
  rail: {
    background: "transparent",
    borderWidth: 0,
    cursor: "ew-resize",
    insetBlock: 0,
    position: "absolute",
    width: "1rem",
    zIndex: 20,
  },
  separator: {
    backgroundColor: colors.sidebarBorder,
    marginInline: "0.5rem",
    width: "auto",
  },
  wrapper: {
    display: "flex",
    minHeight: "100svh",
    width: "100%",
  },
});
