import * as stylex from "@stylexjs/stylex";
import { colors, radius } from "../tokens.stylex";

export const s = stylex.create({
  wrapper: {
    display: "flex",
    minHeight: "100svh",
    width: "100%",
  },
  gap: {
    position: "relative",
    backgroundColor: "transparent",
    transition: "width 0.2s ease-in-out",
  },
  container: {
    position: "fixed",
    top: 0,
    bottom: 0,
    zIndex: 10,
    display: "flex",
    height: "100svh",
    transition: "left 0.2s ease-in-out, right 0.2s ease-in-out, width 0.2s ease-in-out",
  },
  inner: {
    display: "flex",
    height: "100%",
    width: "100%",
    flexDirection: "column",
    backgroundColor: colors.sidebar,
    color: colors.sidebarForeground,
  },
  inset: {
    position: "relative",
    display: "flex",
    width: "100%",
    flex: 1,
    flexDirection: "column",
    backgroundColor: colors.background,
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    padding: "0.5rem",
  },
  footer: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    padding: "0.5rem",
  },
  separator: {
    marginInline: "0.5rem",
    width: "auto",
    backgroundColor: colors.sidebarBorder,
  },
  content: {
    display: "flex",
    minHeight: 0,
    flex: 1,
    flexDirection: "column",
    gap: "0.5rem",
    overflow: "auto",
  },
  group: {
    position: "relative",
    display: "flex",
    width: "100%",
    minWidth: 0,
    flexDirection: "column",
    padding: "0.5rem",
  },
  groupLabel: {
    display: "flex",
    height: "2rem",
    flexShrink: 0,
    alignItems: "center",
    borderRadius: radius.md,
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    fontSize: "0.75rem",
    fontWeight: 500,
    color: `color-mix(in oklab, ${colors.sidebarForeground} 70%, transparent)`,
    outline: "none",
  },
  groupContent: {
    width: "100%",
    fontSize: "0.875rem",
  },
  menu: {
    display: "flex",
    width: "100%",
    minWidth: 0,
    flexDirection: "column",
    gap: "0.25rem",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  menuItem: {
    position: "relative",
  },
  menuButton: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    gap: "0.5rem",
    overflow: "hidden",
    borderRadius: radius.md,
    padding: "0.5rem",
    textAlign: "left",
    fontSize: "0.875rem",
    fontWeight: 400,
    outline: "none",
    transition: "background-color 0.1s ease, color 0.1s ease",
    cursor: "pointer",
    borderWidth: 0,
    backgroundColor: { default: "transparent", ":hover": colors.sidebarAccent },
    color: {
      default: colors.sidebarForeground,
      ":hover": colors.sidebarAccentForeground,
    },
  },
  menuButtonActive: {
    backgroundColor: colors.sidebarAccent,
    color: colors.sidebarAccentForeground,
    fontWeight: 500,
  },
  menuButtonSm: { height: "1.75rem", fontSize: "0.75rem" },
  menuButtonLg: { height: "3rem" },
  menuAction: {
    position: "absolute",
    top: "0.375rem",
    right: "0.25rem",
    display: "flex",
    aspectRatio: "1",
    width: "1.25rem",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.md,
    padding: 0,
    outline: "none",
    cursor: "pointer",
    borderWidth: 0,
    backgroundColor: { default: "transparent", ":hover": colors.sidebarAccent },
    color: colors.sidebarForeground,
  },
  menuBadge: {
    position: "absolute",
    right: "0.25rem",
    top: "0.375rem",
    display: "flex",
    height: "1.25rem",
    minWidth: "1.25rem",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.md,
    paddingLeft: "0.25rem",
    paddingRight: "0.25rem",
    fontSize: "0.75rem",
    fontWeight: 500,
    fontVariantNumeric: "tabular-nums",
    userSelect: "none",
    pointerEvents: "none",
    color: colors.sidebarForeground,
  },
  menuSub: {
    marginLeft: "0.875rem",
    display: "flex",
    minWidth: 0,
    flexDirection: "column",
    gap: "0.25rem",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: colors.sidebarBorder,
    paddingLeft: "0.625rem",
    paddingTop: "0.125rem",
    paddingBottom: "0.125rem",
    listStyle: "none",
  },
  menuSubItem: {
    position: "relative",
  },
  menuSubButton: {
    display: "flex",
    height: "1.75rem",
    minWidth: 0,
    alignItems: "center",
    gap: "0.5rem",
    overflow: "hidden",
    borderRadius: radius.md,
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    outline: "none",
    transition: "background-color 0.1s ease, color 0.1s ease",
    cursor: "pointer",
    textDecorationLine: "none",
    backgroundColor: { default: "transparent", ":hover": colors.sidebarAccent },
    color: {
      default: colors.sidebarForeground,
      ":hover": colors.sidebarAccentForeground,
    },
  },
  menuSubButtonActive: {
    backgroundColor: colors.sidebarAccent,
    color: colors.sidebarAccentForeground,
  },
  menuSkeleton: {
    display: "flex",
    height: "2rem",
    alignItems: "center",
    gap: "0.5rem",
    borderRadius: radius.md,
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
  },
  rail: {
    position: "absolute",
    insetBlock: 0,
    zIndex: 20,
    width: "1rem",
    cursor: "ew-resize",
    borderWidth: 0,
    background: "transparent",
  },
});

