import * as stylex from "@stylexjs/stylex";

import { colors, radius } from "../tokens.stylex";

export const styles = stylex.create({
  groupLabel: {
    color: colors.mutedForeground,
    fontSize: "0.75rem",
    paddingBottom: "0.375rem",
    paddingInline: "0.5rem",
    paddingTop: "0.375rem",
  },
  icon: {
    color: colors.mutedForeground,
    height: "1rem",
    opacity: 0.5,
    pointerEvents: "none",
    width: "1rem",
  },
  item: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.accent, default: "transparent" },
    borderRadius: radius.sm,
    color: {
      ":hover": colors.accentForeground,
      default: colors.popoverForeground,
    },
    cursor: "default",
    display: "flex",
    fontSize: "0.875rem",
    gap: "0.5rem",
    outline: "none",
    paddingBlock: "0.375rem",
    paddingInlineEnd: "2rem",
    paddingInlineStart: "0.5rem",
    position: "relative",
    userSelect: "none",
  },
  itemIndicator: {
    alignItems: "center",
    display: "flex",
    insetInlineEnd: "0.5rem",
    justifyContent: "center",
    position: "absolute",
  },
  popup: {
    backgroundColor: colors.popover,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow:
      "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
    color: colors.popoverForeground,
    maxHeight: "var(--available-height)",
    minWidth: "8rem",
    opacity: 1,
    outline: "none",
    overflowY: "auto",
    padding: "0.25rem",
    transformOrigin: "var(--transform-origin)",
    transition: "opacity 0.15s ease-in-out",
    zIndex: 50,
  },
  popupHidden: { opacity: 0 },
  separator: {
    backgroundColor: colors.border,
    height: "1px",
    marginBlock: "0.25rem",
    marginInline: "-0.25rem",
  },
  trigger: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: { ":focus-visible": colors.ring, default: colors.input },
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: {
      ":focus-visible": `0 0 0 3px color-mix(in oklab, ${colors.ring} 50%, transparent)`,
      default: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    },
    color: colors.foreground,
    cursor: { ":disabled": "not-allowed", default: "pointer" },
    display: "flex",
    fontSize: "0.875rem",
    gap: "0.5rem",
    height: "2.25rem",
    justifyContent: "space-between",
    opacity: { ":disabled": 0.5, default: 1 },
    outline: "none",
    paddingInline: "0.75rem",
    transition: "color 0.15s, box-shadow 0.15s, border-color 0.15s",
    width: "fit-content",
  },
  value: {
    overflow: "hidden",
    textAlign: "start",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
});
