import * as stylex from "@stylexjs/stylex";

import {
  colors,
  radius,
} from "../../../../registry/bases/stylex/lib/tokens.stylex";

const rise = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(6px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

export const createStyles = stylex.create({
  checkbox: { accentColor: colors.primary, height: "1rem", width: "1rem" },
  colorDot: (color: string) => ({ backgroundColor: color }),
  controlMeta: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
  },
  dialogActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
    justifyContent: "flex-end",
  },
  dialogField: { display: "grid", gap: "0.375rem" },
  error: { color: colors.destructive, fontSize: "0.75rem" },
  formGrid: {
    display: "grid",
    gap: "0.75rem",
    gridTemplateColumns: {
      "@media (min-width: 640px)": "1fr 1fr",
      default: "1fr",
    },
  },
  input: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    fontSize: "0.8125rem",
    height: "2.5rem",
    outlineColor: { ":focus-visible": colors.ring, default: "transparent" },
    outlineOffset: 2,
    outlineStyle: "solid",
    outlineWidth: { ":focus-visible": 2, default: 0 },
    paddingInline: "0.75rem",
    width: "100%",
  },
  lockButton: { position: "absolute", right: "0.25rem", top: "1.45rem" },
  optionLabel: { alignItems: "center", display: "flex", gap: "0.5rem" },
  previewBackground: {
    backgroundColor: "color-mix(in oklab, var(--muted) 68%, var(--background))",
    display: "flex",
    flex: 1,
    overflow: "hidden",
    position: "relative",
  },
  previewFrame: { borderWidth: 0, flex: 1, height: "100%", width: "100%" },
  previewScale: (scale: number) => ({
    height: `${10_000 / scale}%`,
    transform: `scale(${scale / 100})`,
    transformOrigin: "top left",
    width: `${10_000 / scale}%`,
  }),
  range: { accentColor: colors.primary, width: "100%" },
  selectWithSwatch: { paddingInlineStart: "2rem" },
  swatch: {
    borderColor: "color-mix(in oklab, currentColor 20%, transparent)",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: 1,
    height: "0.75rem",
    left: "0.625rem",
    pointerEvents: "none",
    position: "absolute",
    top: "2.17rem",
    width: "0.75rem",
    zIndex: 2,
  },
  switchRow: {
    alignItems: "center",
    display: "flex",
    fontSize: "0.8125rem",
    gap: "0.5rem",
    justifyContent: "space-between",
    minHeight: "2rem",
  },
  textarea: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "0.75rem",
    lineHeight: 1.5,
    minHeight: "7rem",
    outlineColor: { ":focus-visible": colors.ring, default: "transparent" },
    outlineOffset: 2,
    outlineStyle: "solid",
    outlineWidth: { ":focus-visible": 2, default: 0 },
    padding: "0.75rem",
    resize: "vertical",
    width: "100%",
  },
  welcomeArt: {
    alignItems: "center",
    backgroundImage:
      "radial-gradient(circle at 30% 20%, color-mix(in oklab, var(--primary) 32%, transparent), transparent 45%), radial-gradient(circle at 70% 80%, color-mix(in oklab, var(--accent) 70%, transparent), transparent 42%)",
    borderRadius: radius.lg,
    display: "flex",
    height: "10rem",
    justifyContent: "center",
  },
  welcomeMark: {
    alignItems: "center",
    backgroundColor: colors.background,
    borderRadius: "1rem",
    boxShadow: "0 16px 45px color-mix(in oklab, black 20%, transparent)",
    display: "flex",
    fontSize: "2rem",
    fontWeight: 700,
    height: "5rem",
    justifyContent: "center",
    width: "5rem",
  },
});

export const designStyles = stylex.create({
  avatar: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: "9999px",
    color: colors.primaryForeground,
    display: "flex",
    flexShrink: 0,
    fontSize: "0.75rem",
    fontWeight: 600,
    height: "2rem",
    justifyContent: "center",
    width: "2rem",
  },
  badge: {
    backgroundColor: colors.secondary,
    borderRadius: "9999px",
    color: colors.secondaryForeground,
    fontSize: "0.6875rem",
    fontWeight: 600,
    paddingBlock: "0.2rem",
    paddingInline: "0.5rem",
  },
  bar: (height: number, color: string) => ({
    backgroundColor: color,
    height,
  }),
  button: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.primary, default: colors.primary },
    borderColor: "transparent",
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.primaryForeground,
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "0.8125rem",
    fontWeight: 500,
    gap: "0.375rem",
    height: "2.25rem",
    justifyContent: "center",
    paddingInline: "0.75rem",
  },
  buttonOutline: {
    backgroundColor: { ":hover": colors.accent, default: colors.background },
    borderColor: colors.border,
    color: colors.foreground,
  },
  buttonSmall: { height: "2rem", paddingInline: "0.625rem" },
  card: {
    animationDuration: "220ms",
    animationName: rise,
    animationTimingFunction: "ease-out",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 1px 2px color-mix(in oklab, black 7%, transparent)",
    color: colors.cardForeground,
    display: "grid",
    gap: "1rem",
    padding: "1rem",
  },
  chart: {
    alignItems: "flex-end",
    display: "flex",
    gap: "0.5rem",
    height: "10rem",
    paddingTop: "1rem",
  },
  chartBar: {
    borderRadius: radius.sm,
    flex: 1,
    minWidth: "0.75rem",
  },
  content: {
    display: "grid",
    flex: 1,
    gap: "1rem",
    minWidth: 0,
    padding: { "@media (min-width: 768px)": "1.5rem", default: "1rem" },
  },
  contentWide: { maxWidth: "86rem", width: "100%" },
  dashboardHeader: {
    alignItems: {
      "@media (min-width: 560px)": "center",
      default: "flex-start",
    },
    display: "flex",
    flexDirection: { "@media (min-width: 560px)": "row", default: "column" },
    gap: "0.75rem",
    justifyContent: "space-between",
  },
  field: { display: "grid", gap: "0.375rem" },
  grid: {
    display: "grid",
    gap: "1rem",
    gridTemplateColumns: {
      "@media (min-width: 720px)": "repeat(2, minmax(0, 1fr))",
      default: "1fr",
    },
  },
  gridThree: {
    gridTemplateColumns: {
      "@media (min-width: 780px)": "repeat(3, minmax(0, 1fr))",
      default: "1fr",
    },
  },
  heading: {
    color: colors.foreground,
    fontFamily: "var(--font-heading)",
    fontSize: "1.125rem",
    fontWeight: 650,
    letterSpacing: "-0.02em",
    margin: 0,
  },
  input: {
    backgroundColor: colors.background,
    borderColor: colors.input,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    fontSize: "0.8125rem",
    height: "2.5rem",
    paddingInline: "0.75rem",
    width: "100%",
  },
  label: {
    color: colors.mutedForeground,
    fontSize: "0.75rem",
    fontWeight: 500,
  },
  list: { display: "grid", gap: "0.25rem" },
  listItem: {
    alignItems: "center",
    borderRadius: radius.md,
    display: "flex",
    gap: "0.75rem",
    justifyContent: "space-between",
    minHeight: "2.75rem",
    paddingInline: "0.5rem",
  },
  menu: {
    backgroundColor: colors.sidebar,
    borderColor: colors.sidebarBorder,
    borderRightStyle: "solid",
    borderRightWidth: 1,
    color: colors.sidebarForeground,
    display: { "@media (min-width: 720px)": "flex", default: "none" },
    flexDirection: "column",
    gap: "0.5rem",
    padding: "1rem",
    width: "13rem",
  },
  menuBold: {
    backgroundColor: colors.sidebarPrimary,
    color: colors.sidebarPrimaryForeground,
  },
  menuBrand: {
    alignItems: "center",
    display: "flex",
    fontFamily: "var(--font-heading)",
    fontSize: "0.875rem",
    fontWeight: 700,
    gap: "0.625rem",
    marginBlockEnd: "0.75rem",
    minHeight: "2.25rem",
  },
  menuItem: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.sidebarAccent, default: "transparent" },
    borderRadius: radius.md,
    color: "inherit",
    display: "flex",
    fontSize: "0.8125rem",
    gap: "0.625rem",
    minHeight: "2.25rem",
    paddingInline: "0.625rem",
  },
  menuTheme: (
    background: string,
    foreground: string,
    accent: string,
    primary: string,
    primaryForeground: string,
    translucent: boolean
  ) => ({
    "--sidebar": translucent
      ? `color-mix(in oklab, ${background} 88%, transparent)`
      : background,
    "--sidebar-accent": accent,
    "--sidebar-accent-foreground": foreground,
    "--sidebar-foreground": foreground,
    "--sidebar-primary": primary,
    "--sidebar-primary-foreground": primaryForeground,
    backdropFilter: translucent ? "blur(18px)" : "none",
  }),
  metric: { color: colors.foreground, fontSize: "1.75rem", fontWeight: 650 },
  muted: { color: colors.mutedForeground, fontSize: "0.75rem" },
  page: {
    backgroundColor: colors.background,
    color: colors.foreground,
    display: "flex",
    fontFamily: "var(--font-body)",
    minHeight: "100svh",
  },
  row: { alignItems: "center", display: "flex", gap: "0.5rem" },
  rowWrap: { flexWrap: "wrap" },
  section: { display: "grid", gap: "0.75rem" },
  spacer: { flex: 1 },
  styleLyra: { letterSpacing: "-0.01em" },
  styleMaia: { "--radius": "1rem" },
  styleMira: { fontSize: "0.9375rem" },
  styleNova: { "--radius": "0.5rem" },
  styleRhea: { "--radius": "0.75rem" },
  styleSera: { letterSpacing: "0.005em" },
  table: { borderCollapse: "collapse", fontSize: "0.75rem", width: "100%" },
  tableCell: {
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    paddingBlock: "0.625rem",
    textAlign: "start",
  },
  tableHead: { color: colors.mutedForeground, fontWeight: 500 },
  theme: (
    background: string,
    foreground: string,
    card: string,
    muted: string,
    mutedForeground: string,
    primary: string,
    primaryForeground: string,
    border: string,
    accent: string,
    radiusValue: string,
    fontBody: string,
    fontHeading: string,
    direction: string,
    cursor: string
  ) => ({
    "--accent": accent,
    "--accent-foreground": foreground,
    "--background": background,
    "--border": border,
    "--card": card,
    "--card-foreground": foreground,
    "--font-body": fontBody,
    "--font-heading": fontHeading,
    "--foreground": foreground,
    "--input": border,
    "--muted": muted,
    "--muted-foreground": mutedForeground,
    "--popover": card,
    "--popover-foreground": foreground,
    "--primary": primary,
    "--primary-foreground": primaryForeground,
    "--radius": radiusValue,
    "--ring": primary,
    "--secondary": muted,
    "--secondary-foreground": foreground,
    "--sidebar": card,
    "--sidebar-accent": accent,
    "--sidebar-accent-foreground": foreground,
    "--sidebar-border": border,
    "--sidebar-foreground": foreground,
    "--sidebar-primary": primary,
    "--sidebar-primary-foreground": primaryForeground,
    "--sidebar-ring": primary,
    cursor,
    direction,
  }),
  title: {
    color: colors.foreground,
    fontFamily: "var(--font-heading)",
    fontSize: "1.5rem",
    fontWeight: 700,
    letterSpacing: "-0.035em",
    margin: 0,
  },
  toolbar: {
    alignItems: "center",
    display: "flex",
    gap: "0.5rem",
    justifyContent: "space-between",
  },
  toolbarBorder: {
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    minHeight: "3rem",
    paddingBlockEnd: "0.75rem",
  },
});
