/* oxlint-disable sort-keys */

import * as stylex from "@stylexjs/stylex";

import {
  colors,
  radius,
} from "../../../../registry/bases/stylex/lib/tokens.stylex";

const rise = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(6px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

export const createStyles = stylex.create({
  checkbox: { accentColor: colors.primary, height: "1rem", width: "1rem" },
  colorDot: (color: string) => ({ backgroundColor: color }),
  controlColorDot: {
    borderColor: "color-mix(in oklab, currentColor 18%, transparent)",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: 1,
    height: "1rem",
    width: "1rem",
  },
  controlMeta: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
  },
  dialogActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
    justifyContent: "flex-end",
  },
  dialogField: { display: "grid", gap: "0.375rem" },
  error: { color: colors.destructive, fontSize: "0.75rem" },
  formGrid: {
    display: "grid",
    gap: "0.75rem",
    gridTemplateColumns: {
      "@media (min-width: 640px)": "1fr 1fr",
      default: "1fr",
    },
  },
  getCodeButton: {
    backgroundColor: { ":hover": colors.primary, default: colors.primary },
    color: colors.primaryForeground,
  },
  input: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    fontSize: "0.8125rem",
    height: "2.5rem",
    outlineColor: { ":focus-visible": colors.ring, default: "transparent" },
    outlineOffset: 2,
    outlineStyle: "solid",
    outlineWidth: { ":focus-visible": 2, default: 0 },
    paddingInline: "0.75rem",
    width: "100%",
  },
  lockButton: { position: "absolute", right: "0.25rem", top: "1.45rem" },
  optionLabel: { alignItems: "center", display: "flex", gap: "0.5rem" },
  previewBackground: {
    backgroundColor: "color-mix(in oklab, var(--muted) 68%, var(--background))",
    display: "flex",
    flex: 1,
    overflow: "hidden",
    position: "relative",
  },
  previewFrame: { borderWidth: 0, flex: 1, height: "100%", width: "100%" },
  previewShell: {
    backgroundColor: colors.background,
    borderRadius: "1rem",
    boxShadow:
      "0 0 0 1px color-mix(in oklab, var(--foreground) 10%, transparent)",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    height: "100%",
    isolation: "isolate",
    justifyContent: "center",
    minHeight: { default: "30rem", "@media (min-width: 768px)": 0 },
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  previewScale: (scale: number) => ({
    height: `${10_000 / scale}%`,
    transform: `scale(${scale / 100})`,
    transformOrigin: "top left",
    width: `${10_000 / scale}%`,
  }),
  previewSwitchButton: {
    backgroundColor: {
      default: "transparent",
      "[data-active='true']": "oklch(0.371 0 0)",
    },
    borderRadius: "0.5rem",
    borderWidth: 0,
    color: {
      default: "oklch(0.708 0 0)",
      "[data-active='true']": "oklch(0.985 0 0)",
    },
    cursor: "pointer",
    fontSize: "0.75rem",
    fontWeight: 500,
    height: "1.75rem",
    minWidth: "2rem",
    paddingInline: "0.625rem",
  },
  previewSwitcher: {
    alignItems: "center",
    backdropFilter: "blur(20px)",
    backgroundColor: "oklch(0.205 0 0 / 90%)",
    borderRadius: "0.75rem",
    bottom: "0.75rem",
    boxShadow: "0 12px 32px color-mix(in oklab, black 28%, transparent)",
    display: "flex",
    gap: "0.25rem",
    padding: "0.25rem",
    position: "absolute",
    right: "0.75rem",
    zIndex: 20,
  },
  range: { accentColor: colors.primary, width: "100%" },
  resetButton: {
    display: { default: "inline-flex", "@media (min-width: 768px)": "none" },
  },
  selectWithSwatch: { paddingInlineStart: "2rem" },
  swatch: {
    borderColor: "color-mix(in oklab, currentColor 20%, transparent)",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: 1,
    height: "0.75rem",
    left: "0.625rem",
    pointerEvents: "none",
    position: "absolute",
    top: "2.17rem",
    width: "0.75rem",
    zIndex: 2,
  },
  switchRow: {
    alignItems: "center",
    display: "flex",
    fontSize: "0.8125rem",
    gap: "0.5rem",
    justifyContent: "space-between",
    minHeight: "2rem",
  },
  textarea: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "0.75rem",
    lineHeight: 1.5,
    minHeight: "7rem",
    outlineColor: { ":focus-visible": colors.ring, default: "transparent" },
    outlineOffset: 2,
    outlineStyle: "solid",
    outlineWidth: { ":focus-visible": 2, default: 0 },
    padding: "0.75rem",
    resize: "vertical",
    width: "100%",
  },
  welcomeArt: {
    alignItems: "center",
    backgroundImage:
      "radial-gradient(circle at 30% 20%, color-mix(in oklab, var(--primary) 32%, transparent), transparent 45%), radial-gradient(circle at 70% 80%, color-mix(in oklab, var(--accent) 70%, transparent), transparent 42%)",
    borderRadius: radius.lg,
    display: "flex",
    height: "10rem",
    justifyContent: "center",
  },
  welcomeMark: {
    alignItems: "center",
    backgroundColor: colors.background,
    borderRadius: "1rem",
    boxShadow: "0 16px 45px color-mix(in oklab, black 20%, transparent)",
    display: "flex",
    fontSize: "2rem",
    fontWeight: 700,
    height: "5rem",
    justifyContent: "center",
    width: "5rem",
  },
});

export const designStyles = stylex.create({
  avatar: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: "9999px",
    color: colors.primaryForeground,
    display: "flex",
    flexShrink: 0,
    fontSize: "0.75rem",
    fontWeight: 600,
    height: "2rem",
    justifyContent: "center",
    width: "2rem",
  },
  badge: {
    backgroundColor: colors.secondary,
    borderRadius: "9999px",
    color: colors.secondaryForeground,
    fontSize: "0.6875rem",
    fontWeight: 600,
    paddingBlock: "0.2rem",
    paddingInline: "0.5rem",
  },
  bar: (height: number, color: string) => ({
    backgroundColor: color,
    height,
  }),
  button: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.primary, default: colors.primary },
    borderColor: "transparent",
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.primaryForeground,
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "0.8125rem",
    fontWeight: 500,
    gap: "0.375rem",
    height: "2.25rem",
    justifyContent: "center",
    paddingInline: "0.75rem",
  },
  buttonOutline: {
    backgroundColor: { ":hover": colors.accent, default: colors.background },
    borderColor: colors.border,
    color: colors.foreground,
  },
  buttonSmall: { height: "2rem", paddingInline: "0.625rem" },
  card: {
    animationDuration: "220ms",
    animationName: rise,
    animationTimingFunction: "ease-out",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 1px 2px color-mix(in oklab, black 7%, transparent)",
    color: colors.cardForeground,
    display: "grid",
    gap: "1rem",
    padding: "1rem",
  },
  chart: {
    alignItems: "flex-end",
    display: "flex",
    gap: "0.5rem",
    height: "10rem",
    paddingTop: "1rem",
  },
  chartBar: {
    borderRadius: radius.sm,
    flex: 1,
    minWidth: "0.75rem",
  },
  content: {
    display: "grid",
    flex: 1,
    gap: "1rem",
    minWidth: 0,
    padding: { "@media (min-width: 768px)": "1.5rem", default: "1rem" },
  },
  contentWide: { maxWidth: "86rem", width: "100%" },
  dashboardHeader: {
    alignItems: {
      "@media (min-width: 560px)": "center",
      default: "flex-start",
    },
    display: "flex",
    flexDirection: { "@media (min-width: 560px)": "row", default: "column" },
    gap: "0.75rem",
    justifyContent: "space-between",
  },
  dashboardBlockBody: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: "1.5rem",
    paddingBlock: "1.5rem",
    paddingInline: "1.5rem",
  },
  dashboardBlockHeader: {
    alignItems: "center",
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexShrink: 0,
    height: "3.5rem",
    justifyContent: "space-between",
    paddingInline: "1.5rem",
  },
  dashboardBlockHeaderExample: { height: "3rem" },
  dashboardBlockMain: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  dashboardBlockTitle: {
    fontSize: "1rem",
    fontWeight: 500,
    margin: 0,
  },
  dashboardBrand: {
    alignItems: "center",
    display: "flex",
    fontSize: "1rem",
    fontWeight: 600,
    gap: "0.625rem",
    height: "2.5rem",
    paddingInline: "0.5rem",
  },
  dashboardDelta: {
    alignItems: "center",
    borderColor: colors.border,
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: 1,
    display: "inline-flex",
    fontSize: "0.75rem",
    gap: "0.25rem",
    paddingBlock: "0.125rem",
    paddingInline: "0.5rem",
  },
  dashboardGithub: {
    color: colors.foreground,
    fontSize: "0.875rem",
    textDecoration: "none",
  },
  dashboardHeaderSeparator: {
    backgroundColor: colors.border,
    height: "1rem",
    marginInline: "0.5rem",
    width: 1,
  },
  dashboardMenu: {
    backgroundColor: colors.muted,
    borderRightColor: colors.border,
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: { default: "none", "@media (min-width: 720px)": "flex" },
    flexDirection: "column",
    flexShrink: 0,
    gap: "0.25rem",
    padding: "0.75rem",
    width: "18rem",
  },
  dashboardMenuExample: { width: "16rem" },
  dashboardMenuItem: {
    alignItems: "center",
    borderRadius: radius.md,
    display: "flex",
    fontSize: "0.875rem",
    gap: "0.625rem",
    minHeight: "2.25rem",
    paddingInline: "0.625rem",
  },
  dashboardMenuLabel: {
    color: colors.mutedForeground,
    fontSize: "0.75rem",
    marginBlockStart: "0.75rem",
    paddingInline: "0.625rem",
  },
  dashboardMessageButton: {
    alignItems: "center",
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    display: "flex",
    height: "2rem",
    justifyContent: "center",
    width: "2rem",
  },
  dashboardMetricCard: {
    backgroundImage:
      "linear-gradient(to top, color-mix(in oklab, var(--primary) 5%, transparent), var(--card))",
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 1px 2px color-mix(in oklab, black 5%, transparent)",
    display: "flex",
    flexDirection: "column",
    gap: "0.875rem",
    height: "12.5rem",
    padding: "1.5rem",
  },
  dashboardMetricDetail: {
    alignItems: "center",
    display: "flex",
    fontSize: "0.875rem",
    fontWeight: 500,
    gap: "0.375rem",
  },
  dashboardMetricFooter: {
    display: "grid",
    gap: "0.375rem",
    marginBlockStart: "auto",
  },
  dashboardMetricGrid: {
    display: "grid",
    gap: "1rem",
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 760px)": "repeat(2, minmax(0, 1fr))",
      "@media (min-width: 1120px)": "repeat(4, minmax(0, 1fr))",
    },
  },
  dashboardMetricHeader: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
  },
  dashboardQuickCreate: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderColor: "transparent",
    borderRadius: radius.md,
    borderWidth: 0,
    color: colors.primaryForeground,
    display: "flex",
    flex: 1,
    fontSize: "0.875rem",
    gap: "0.625rem",
    height: "2rem",
    paddingInline: "0.625rem",
  },
  dashboardQuickCreateHeader: { flex: "none" },
  dashboardQuickRow: {
    display: "flex",
    gap: "0.5rem",
    marginBlock: "0.25rem",
  },
  field: { display: "grid", gap: "0.375rem" },
  grid: {
    display: "grid",
    gap: "1rem",
    gridTemplateColumns: {
      "@media (min-width: 720px)": "repeat(2, minmax(0, 1fr))",
      default: "1fr",
    },
  },
  gridThree: {
    gridTemplateColumns: {
      "@media (min-width: 780px)": "repeat(3, minmax(0, 1fr))",
      default: "1fr",
    },
  },
  heading: {
    color: colors.foreground,
    fontFamily: "var(--font-heading)",
    fontSize: "1.125rem",
    fontWeight: 650,
    letterSpacing: "-0.02em",
    margin: 0,
  },
  input: {
    backgroundColor: colors.background,
    borderColor: colors.input,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    fontSize: "0.8125rem",
    height: "2.5rem",
    paddingInline: "0.75rem",
    width: "100%",
  },
  label: {
    color: colors.mutedForeground,
    fontSize: "0.75rem",
    fontWeight: 500,
  },
  list: { display: "grid", gap: "0.25rem" },
  listItem: {
    alignItems: "center",
    borderRadius: radius.md,
    display: "flex",
    gap: "0.75rem",
    justifyContent: "space-between",
    minHeight: "2.75rem",
    paddingInline: "0.5rem",
  },
  menu: {
    backgroundColor: colors.sidebar,
    borderColor: colors.sidebarBorder,
    borderRightStyle: "solid",
    borderRightWidth: 1,
    color: colors.sidebarForeground,
    display: { "@media (min-width: 720px)": "flex", default: "none" },
    flexDirection: "column",
    gap: "0.5rem",
    padding: "1rem",
    width: "13rem",
  },
  menuBold: {
    backgroundColor: colors.sidebarPrimary,
    color: colors.sidebarPrimaryForeground,
  },
  menuBrand: {
    alignItems: "center",
    display: "flex",
    fontFamily: "var(--font-heading)",
    fontSize: "0.875rem",
    fontWeight: 700,
    gap: "0.625rem",
    marginBlockEnd: "0.75rem",
    minHeight: "2.25rem",
  },
  menuItem: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.sidebarAccent, default: "transparent" },
    borderRadius: radius.md,
    color: "inherit",
    display: "flex",
    fontSize: "0.8125rem",
    gap: "0.625rem",
    minHeight: "2.25rem",
    paddingInline: "0.625rem",
  },
  menuTheme: (
    background: string,
    foreground: string,
    accent: string,
    primary: string,
    primaryForeground: string,
    translucent: boolean
  ) => ({
    "--sidebar": translucent
      ? `color-mix(in oklab, ${background} 88%, transparent)`
      : background,
    "--sidebar-accent": accent,
    "--sidebar-accent-foreground": foreground,
    "--sidebar-foreground": foreground,
    "--sidebar-primary": primary,
    "--sidebar-primary-foreground": primaryForeground,
    backdropFilter: translucent ? "blur(18px)" : "none",
  }),
  metric: { color: colors.foreground, fontSize: "1.75rem", fontWeight: 650 },
  muted: { color: colors.mutedForeground, fontSize: "0.75rem" },
  page: {
    backgroundColor: colors.background,
    color: colors.foreground,
    display: "flex",
    fontFamily: "var(--font-body)",
    minHeight: "100svh",
  },
  row: { alignItems: "center", display: "flex", gap: "0.5rem" },
  rowWrap: { flexWrap: "wrap" },
  section: { display: "grid", gap: "0.75rem" },
  spacer: { flex: 1 },
  styleLyra: { letterSpacing: "-0.01em" },
  styleMaia: { "--radius": "1rem" },
  styleMira: { fontSize: "0.9375rem" },
  styleNova: { "--radius": "0.5rem" },
  styleRhea: { "--radius": "0.75rem" },
  styleSera: { letterSpacing: "0.005em" },
  table: { borderCollapse: "collapse", fontSize: "0.75rem", width: "100%" },
  tableCell: {
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    paddingBlock: "0.625rem",
    textAlign: "start",
  },
  tableHead: { color: colors.mutedForeground, fontWeight: 500 },
  showcaseAdd: {
    alignItems: "center",
    backgroundColor: colors.muted,
    borderRadius: radius.md,
    display: "flex",
    fontSize: "1.25rem",
    height: "2rem",
    justifyContent: "center",
    width: "2rem",
  },
  showcaseAmount: { fontSize: "1.5rem", fontWeight: 500 },
  showcaseBalance: { fontSize: "3.25rem", fontWeight: 400, lineHeight: 1 },
  showcaseBar: {
    borderRadius: "0.375rem 0.375rem 0 0",
    display: "block",
    width: "2.5rem",
  },
  showcaseBarColumn: {
    alignItems: "center",
    color: colors.mutedForeground,
    display: "flex",
    flex: 1,
    flexDirection: "column",
    fontSize: "0.75rem",
    gap: "0.5rem",
    justifyContent: "flex-end",
  },
  showcaseBarValue: (height: number, color: string) => ({
    backgroundColor: color,
    height,
  }),
  showcaseBars: {
    alignItems: "flex-end",
    display: "flex",
    gap: "0.75rem",
    height: "11rem",
  },
  showcaseButton: {
    backgroundColor: colors.primary,
    borderColor: "transparent",
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 0,
    color: colors.primaryForeground,
    cursor: "pointer",
    fontSize: "0.875rem",
    fontWeight: 500,
    height: "2rem",
    paddingInline: "1rem",
    width: "100%",
  },
  showcaseButtonFit: { width: "fit-content" },
  showcaseCanvas: {
    backgroundColor: colors.muted,
    flex: 1,
    minHeight: "100svh",
    minWidth: "76rem",
    overflow: "hidden",
    padding: "2.75rem",
    width: "100%",
  },
  showcaseCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.cardForeground,
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    overflow: "hidden",
    padding: "1rem",
  },
  showcaseCentered: { maxWidth: "19rem", textAlign: "center" },
  showcaseColumn: { display: "flex", flexDirection: "column", gap: "2.5rem" },
  showcaseDescription: {
    color: colors.mutedForeground,
    fontSize: "0.875rem",
    lineHeight: 1.45,
    margin: 0,
  },
  showcaseEmpty: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: "15rem",
    textAlign: "center",
  },
  showcaseEyebrow: {
    color: colors.mutedForeground,
    fontSize: "0.6875rem",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  },
  showcaseField: { display: "grid", fontSize: "0.875rem", gap: "0.5rem" },
  showcaseFooter: {
    borderTopColor: colors.border,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    margin: "0 -1rem -1rem",
    padding: "1rem",
  },
  showcaseFooterText: {
    borderTopColor: colors.border,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    color: colors.mutedForeground,
    margin: "0 -1rem -1rem",
    padding: "1rem",
  },
  showcaseGrid: {
    display: "grid",
    gap: "2.75rem",
    gridTemplateColumns: "repeat(3, 23.5rem)",
  },
  showcaseIconButton: {
    backgroundColor: colors.muted,
    borderWidth: 0,
    borderRadius: radius.md,
    fontSize: "1.25rem",
    height: "2rem",
    width: "2rem",
  },
  showcaseInput: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    fontSize: "0.875rem",
    height: "2.25rem",
    paddingInline: "0.625rem",
    width: "100%",
  },
  showcaseInset: {
    backgroundColor: colors.muted,
    borderRadius: radius.md,
    display: "grid",
    gap: "0.375rem",
    padding: "0.75rem",
  },
  showcaseProgress: {
    backgroundColor: colors.primary,
    display: "block",
    height: "0.25rem",
  },
  showcaseProgressValue: (width: string) => ({ width }),
  showcaseSplit: {
    display: "grid",
    gap: "0.75rem",
    gridTemplateColumns: "1fr 1fr",
  },
  showcaseStatus: {
    borderColor: colors.border,
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: 1,
    fontSize: "0.75rem",
    padding: "0.125rem 0.5rem",
    width: "fit-content",
  },
  showcaseTarget: {
    backgroundColor: colors.muted,
    display: "grid",
    gap: "0.5rem",
    marginInline: "-1rem",
    padding: "1rem",
  },
  showcaseTargetValue: { fontSize: "2rem", fontWeight: 600 },
  showcaseTextarea: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    fontFamily: "inherit",
    fontSize: "0.875rem",
    minHeight: "6.25rem",
    padding: "0.625rem",
    resize: "vertical",
  },
  showcaseTitle: { fontSize: "1.125rem", fontWeight: 500, margin: 0 },
  showcaseToolbar: {
    alignItems: "flex-start",
    display: "flex",
    gap: "0.75rem",
    justifyContent: "space-between",
  },
  showcaseTransaction: {
    alignItems: "center",
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: "0.75rem",
    paddingBlock: "0.625rem",
  },
  showcaseTransactionIcon: {
    alignItems: "center",
    backgroundColor: colors.muted,
    borderRadius: radius.md,
    display: "flex",
    height: "2.5rem",
    justifyContent: "center",
    width: "2.5rem",
  },
  showcaseTransactions: { display: "grid" },
  authBrand: {
    alignItems: "center",
    display: "flex",
    fontSize: "1.125rem",
    fontWeight: 600,
    gap: "0.5rem",
    position: "relative",
    zIndex: 1,
  },
  authBrandPanel: {
    backgroundColor:
      "color-mix(in oklab, var(--primary) 5%, var(--background))",
    color: colors.primary,
    display: { default: "none", "@media (min-width: 1024px)": "flex" },
    flexDirection: "column",
    minHeight: "62.5rem",
    padding: "2.5rem",
  },
  authDivider: {
    alignItems: "center",
    color: colors.mutedForeground,
    display: "flex",
    fontSize: "0.6875rem",
    justifyContent: "center",
    letterSpacing: "0.08em",
    minHeight: "1.5rem",
  },
  authForm: {
    display: "grid",
    gap: "1rem",
    maxWidth: "21.875rem",
    width: "100%",
  },
  authFormHeader: { display: "grid", gap: "0.5rem", textAlign: "center" },
  authFormPanel: {
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
    minHeight: "62.5rem",
    padding: "2rem",
    position: "relative",
  },
  authLogin: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: colors.foreground,
    cursor: "pointer",
    fontSize: "0.875rem",
    position: "absolute",
    right: "2rem",
    top: "2rem",
  },
  authPage: {
    display: "grid",
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 1024px)": "1fr 1fr",
    },
    minHeight: "100svh",
    width: "100%",
  },
  authQuote: {
    lineHeight: 1.6,
    margin: 0,
    marginBlockStart: "auto",
    maxWidth: "36rem",
    position: "relative",
    zIndex: 1,
  },
  authTerms: {
    color: colors.mutedForeground,
    fontSize: "0.75rem",
    lineHeight: 1.6,
    margin: 0,
    paddingInline: "1.5rem",
    textAlign: "center",
  },
  examplePage: {
    display: "block",
    minHeight: "100svh",
    overflow: "auto",
    width: "100%",
  },
  playgroundBody: {
    display: "grid",
    flex: 1,
    gap: "1.5rem",
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 768px)": "minmax(0, 1fr) 12.5rem",
    },
    padding: "1.5rem",
  },
  playgroundControls: {
    display: "flex",
    flexDirection: "column",
    gap: "1.5rem",
  },
  playgroundHeader: {
    alignItems: "center",
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    justifyContent: "space-between",
    minHeight: "4rem",
    paddingInline: "1.5rem",
  },
  playgroundModes: {
    backgroundColor: colors.muted,
    borderRadius: radius.md,
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    padding: "0.25rem",
  },
  playgroundPage: {
    display: "flex",
    flexDirection: "column",
    minHeight: "56rem",
  },
  playgroundPreset: { width: "11rem" },
  playgroundPrompt: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    minHeight: "43.75rem",
  },
  playgroundTextarea: {
    backgroundColor: colors.background,
    borderColor: colors.input,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    flex: 1,
    fontFamily: "inherit",
    fontSize: "0.875rem",
    minHeight: "25rem",
    padding: "1rem",
    resize: "vertical",
    width: "100%",
  },
  rtlPage: { display: "grid", gap: "2rem", padding: "2rem" },
  rtlTextarea: { minHeight: "12rem" },
  switchRow: {
    alignItems: "center",
    display: "flex",
    fontSize: "0.875rem",
    justifyContent: "space-between",
    minHeight: "2.25rem",
  },
  tasksFilter: { maxWidth: "20rem" },
  tasksPage: {
    display: "flex",
    flexDirection: "column",
    gap: "2rem",
    padding: "2rem",
  },
  tasksTableShell: {
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
  },
  tasksToolbar: {
    alignItems: "center",
    display: "flex",
    gap: "0.5rem",
  },
  tasksView: { marginInlineStart: "auto" },
  theme: (
    background: string,
    foreground: string,
    card: string,
    muted: string,
    mutedForeground: string,
    primary: string,
    primaryForeground: string,
    border: string,
    accent: string,
    radiusValue: string,
    fontBody: string,
    fontHeading: string,
    direction: string,
    cursor: string
  ) => ({
    "--accent": accent,
    "--accent-foreground": foreground,
    "--background": background,
    "--border": border,
    "--card": card,
    "--card-foreground": foreground,
    "--font-body": fontBody,
    "--font-heading": fontHeading,
    "--foreground": foreground,
    "--input": border,
    "--muted": muted,
    "--muted-foreground": mutedForeground,
    "--popover": card,
    "--popover-foreground": foreground,
    "--primary": primary,
    "--primary-foreground": primaryForeground,
    "--radius": radiusValue,
    "--ring": primary,
    "--secondary": muted,
    "--secondary-foreground": foreground,
    "--sidebar": card,
    "--sidebar-accent": accent,
    "--sidebar-accent-foreground": foreground,
    "--sidebar-border": border,
    "--sidebar-foreground": foreground,
    "--sidebar-primary": primary,
    "--sidebar-primary-foreground": primaryForeground,
    "--sidebar-ring": primary,
    cursor,
    direction,
  }),
  title: {
    color: colors.foreground,
    fontFamily: "var(--font-heading)",
    fontSize: "1.5rem",
    fontWeight: 700,
    letterSpacing: "-0.035em",
    margin: 0,
  },
  toolbar: {
    alignItems: "center",
    display: "flex",
    gap: "0.5rem",
    justifyContent: "space-between",
  },
  toolbarBorder: {
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    minHeight: "3rem",
    paddingBlockEnd: "0.75rem",
  },
});
