import * as stylex from "@stylexjs/stylex";

import { colors, radius } from "../../registry/bases/stylex/tokens.stylex";

export const styles = stylex.create({
  actionRow: { display: "flex", flexWrap: "wrap", gap: "0.5rem" },
  article: { color: colors.foreground, marginInline: "auto", width: "100%" },
  articleBody: { display: "grid", gap: "1.25em" },
  button: {
    backgroundColor: colors.secondary,
    border: 0,
    borderRadius: radius.md,
    color: colors.secondaryForeground,
    cursor: "pointer",
    fontSize: "0.8125rem",
    fontWeight: 500,
    minHeight: "2.25rem",
    paddingInline: "0.875rem",
  },
  code: {
    backgroundColor: colors.muted,
    borderRadius: radius.sm,
    display: "block",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "0.75rem",
    maxHeight: "18rem",
    overflow: "auto",
    padding: "1rem",
    whiteSpace: "pre",
  },
  control: { display: "grid", gap: "0.375rem" },
  controlGrid: {
    display: "grid",
    gap: "1rem",
    gridTemplateColumns: "repeat(auto-fit, minmax(10rem, 1fr))",
  },
  input: { accentColor: colors.primary, width: "100%" },
  label: {
    color: colors.mutedForeground,
    fontSize: "0.75rem",
    fontWeight: 500,
  },
  layout: {
    display: "grid",
    gap: "1rem",
    gridTemplateColumns: {
      "@media (min-width: 64rem)": "20rem minmax(0, 1fr)",
      default: "minmax(0, 1fr)",
    },
    marginInline: "auto",
    maxWidth: "96rem",
    padding: "1rem",
    width: "100%",
  },
  panel: {
    backgroundColor: colors.card,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.xl,
    display: "grid",
    gap: "1rem",
    padding: "1rem",
  },
  preview: {
    backgroundColor: colors.background,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.xl,
    minHeight: "calc(100svh - 9rem)",
    overflow: "auto",
    padding: { "@media (min-width: 48rem)": "4rem", default: "1.5rem" },
  },
  root: { backgroundColor: colors.muted, flex: 1, minHeight: 0 },
  select: {
    backgroundColor: colors.background,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    color: colors.foreground,
    minHeight: "2.25rem",
    paddingInline: "0.625rem",
    width: "100%",
  },
  title: { fontSize: "1.125rem", fontWeight: 600 },
});
