// oxlint-disable sort-keys -- grouped by concern (spacing, color, radii) for clarity
import { createConfig } from "@tokenami/css";

/**
 * Tokenami configuration for the Tokenami component base.
 *
 * Each theme token wraps the corresponding CSS custom property defined in the
 * app's global stylesheet (e.g. `--primary`). Theming therefore stays driven by
 * the class-based `.dark` toggle (next-themes) and the theme customizer —
 * flipping `.dark` / changing `--primary` updates the underlying variables,
 * which propagate through these tokens. Components reference
 * `var(--color_primary)` / `var(--radii_md)` instead of the raw shadcn
 * variables so usage is typed and centralized, mirroring the StyleX base.
 */
export default createConfig({
  include: [
    "./registry/bases/tokenami/**/*.{ts,tsx}",
    "./examples-tokenami/**/*.{ts,tsx}",
  ],
  // Match Tailwind's spacing scale: a numeric value of `4` => `1rem`.
  grid: "0.25rem",
  responsive: {
    lg: "@media (min-width: 1024px)",
    md: "@media (min-width: 768px)",
    sm: "@media (min-width: 640px)",
  },
  selectors: {
    // Native pseudo-classes / elements
    hover: "&:hover",
    focus: "&:focus",
    "focus-visible": "&:focus-visible",
    "focus-within": "&:focus-within",
    active: "&:active",
    disabled: "&:disabled",
    "placeholder-shown": "&:placeholder-shown",
    "first-child": "&:first-child",
    "last-child": "&:last-child",
    before: "&::before",
    after: "&::after",
    placeholder: "&::placeholder",
    selection: "&::selection",
    "file-selector-button": "&::file-selector-button",
    // Base UI state data-attributes (Tokenami, unlike StyleX, supports them).
    open: "&[data-open]",
    closed: "&[data-closed]",
    "panel-open": "&[data-panel-open]",
    highlighted: "&[data-highlighted]",
    selected: "&[data-selected]",
    checked: "&[data-checked]",
    unchecked: "&[data-unchecked]",
    pressed: "&[data-pressed]",
    "data-active": "&[data-active]",
    "data-disabled": "&[data-disabled]",
    invalid: "&[data-invalid]",
    "aria-invalid": "&[aria-invalid='true']",
    starting: "&[data-starting-style]",
    ending: "&[data-ending-style]",
  },
  theme: {
    color: {
      accent: "var(--accent)",
      "accent-foreground": "var(--accent-foreground)",
      background: "var(--background)",
      border: "var(--border)",
      card: "var(--card)",
      "card-foreground": "var(--card-foreground)",
      current: "currentColor",
      destructive: "var(--destructive)",
      foreground: "var(--foreground)",
      input: "var(--input)",
      muted: "var(--muted)",
      "muted-foreground": "var(--muted-foreground)",
      popover: "var(--popover)",
      "popover-foreground": "var(--popover-foreground)",
      primary: "var(--primary)",
      "primary-foreground": "var(--primary-foreground)",
      ring: "var(--ring)",
      secondary: "var(--secondary)",
      "secondary-foreground": "var(--secondary-foreground)",
      sidebar: "var(--sidebar)",
      "sidebar-accent": "var(--sidebar-accent)",
      "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
      "sidebar-border": "var(--sidebar-border)",
      "sidebar-foreground": "var(--sidebar-foreground)",
      "sidebar-primary": "var(--sidebar-primary)",
      "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
      "sidebar-ring": "var(--sidebar-ring)",
      transparent: "transparent",
    },
    radii: {
      full: "9999px",
      lg: "var(--radius)",
      md: "calc(var(--radius) - 2px)",
      sm: "calc(var(--radius) - 4px)",
      xl: "calc(var(--radius) + 4px)",
    },
  },
  aliases: {},
  customProperties: {},
  // Associate properties with theme keys so token values are typed. Numeric
  // (grid) properties accept plain numbers (multiplied by `grid`); color/radii
  // properties accept their respective tokens. Properties left unmapped fall
  // back to their native CSS value types (keywords + arbitrary).
  properties: {
    // Spacing & sizing (grid multiples)
    gap: ["grid"],
    "row-gap": ["grid"],
    "column-gap": ["grid"],
    width: ["grid"],
    height: ["grid"],
    "min-width": ["grid"],
    "min-height": ["grid"],
    "max-width": ["grid"],
    "max-height": ["grid"],
    size: ["grid"],
    padding: ["grid"],
    "padding-top": ["grid"],
    "padding-right": ["grid"],
    "padding-bottom": ["grid"],
    "padding-left": ["grid"],
    "padding-inline": ["grid"],
    "padding-block": ["grid"],
    "padding-inline-start": ["grid"],
    "padding-inline-end": ["grid"],
    "padding-block-start": ["grid"],
    "padding-block-end": ["grid"],
    margin: ["grid"],
    "margin-top": ["grid"],
    "margin-right": ["grid"],
    "margin-bottom": ["grid"],
    "margin-left": ["grid"],
    "margin-inline": ["grid"],
    "margin-block": ["grid"],
    "margin-inline-start": ["grid"],
    "margin-inline-end": ["grid"],
    top: ["grid"],
    right: ["grid"],
    bottom: ["grid"],
    left: ["grid"],
    inset: ["grid"],
    "inset-inline": ["grid"],
    "inset-block": ["grid"],
    "border-width": ["grid"],
    "border-top-width": ["grid"],
    "border-right-width": ["grid"],
    "border-bottom-width": ["grid"],
    "border-left-width": ["grid"],
    "border-inline-width": ["grid"],
    "border-block-width": ["grid"],
    "border-inline-start-width": ["grid"],
    "border-inline-end-width": ["grid"],
    translate: ["grid"],
    // Colors
    color: ["color"],
    background: ["color"],
    "background-color": ["color"],
    "border-color": ["color"],
    "border-top-color": ["color"],
    "border-right-color": ["color"],
    "border-bottom-color": ["color"],
    "border-left-color": ["color"],
    "border-inline-color": ["color"],
    "border-block-color": ["color"],
    "border-inline-start-color": ["color"],
    "border-inline-end-color": ["color"],
    "outline-color": ["color"],
    "text-decoration-color": ["color"],
    "caret-color": ["color"],
    fill: ["color"],
    stroke: ["color"],
    // Radii
    "border-radius": ["radii"],
    "border-top-left-radius": ["radii"],
    "border-top-right-radius": ["radii"],
    "border-bottom-left-radius": ["radii"],
    "border-bottom-right-radius": ["radii"],
    "border-start-start-radius": ["radii"],
    "border-start-end-radius": ["radii"],
    "border-end-start-radius": ["radii"],
    "border-end-end-radius": ["radii"],
  },
  themeSelector: () => ":root",
});
