import * as stylex from "@stylexjs/stylex";

import { colors, radius } from "../tokens.stylex";

export const styles = stylex.create({
  command: {
    backgroundColor: colors.popover,
    borderRadius: radius.md,
    color: colors.popoverForeground,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    overflow: "hidden",
    width: "100%",
  },
  empty: {
    color: colors.mutedForeground,
    fontSize: "0.875rem",
    paddingBlock: "1.5rem",
    textAlign: "center",
  },
  group: {
    color: colors.foreground,
    overflow: "hidden",
    padding: "0.25rem",
  },
  groupHeading: {
    color: colors.mutedForeground,
    fontSize: "0.75rem",
    fontWeight: 500,
    paddingBlock: "0.375rem",
    paddingInline: "0.5rem",
  },
  input: {
    "::placeholder": { color: colors.mutedForeground },
    backgroundColor: "transparent",
    borderWidth: 0,
    color: colors.foreground,
    display: "flex",
    flex: 1,
    fontSize: "0.875rem",
    height: "3rem",
    outline: "none",
    paddingBottom: "0.75rem",
    paddingTop: "0.75rem",
    width: "100%",
  },
  inputIcon: {
    color: colors.mutedForeground,
    flexShrink: 0,
    height: "1rem",
    opacity: 0.5,
    width: "1rem",
  },
  inputWrapper: {
    alignItems: "center",
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: "0.5rem",
    height: "3rem",
    paddingInline: "0.75rem",
  },
  item: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.accent, default: "transparent" },
    borderRadius: "0.125rem",
    color: { ":hover": colors.accentForeground, default: "inherit" },
    cursor: "default",
    display: "flex",
    fontSize: "0.875rem",
    gap: "0.5rem",
    outline: "none",
    paddingBlock: "0.375rem",
    paddingInline: "0.5rem",
    position: "relative",
    transition: "background-color 0.1s ease, color 0.1s ease",
    userSelect: "none",
  },
  list: {
    maxHeight: "300px",
    overflowX: "hidden",
    overflowY: "auto",
    scrollPaddingBlock: "0.25rem",
  },
  separator: {
    backgroundColor: colors.border,
    height: "1px",
    marginInline: "-0.25rem",
  },
  shortcut: {
    color: colors.mutedForeground,
    fontSize: "0.75rem",
    letterSpacing: "0.05em",
    marginInlineStart: "auto",
  },
  srOnly: {
    borderWidth: 0,
    clip: "rect(0, 0, 0, 0)",
    height: "1px",
    margin: "-1px",
    overflow: "hidden",
    padding: 0,
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
});
