import * as stylex from "@stylexjs/stylex";
import { colors, radius } from "../tokens.stylex";

export const styles = stylex.create({
  command: {
    display: "flex",
    height: "100%",
    width: "100%",
    flexDirection: "column",
    overflow: "hidden",
    borderRadius: radius.md,
    backgroundColor: colors.popover,
    color: colors.popoverForeground,
  },
  inputWrapper: {
    display: "flex",
    height: "3rem",
    alignItems: "center",
    gap: "0.5rem",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    paddingInline: "0.75rem",
  },
  inputIcon: {
    width: "1rem",
    height: "1rem",
    flexShrink: 0,
    opacity: 0.5,
    color: colors.mutedForeground,
  },
  input: {
    display: "flex",
    height: "3rem",
    width: "100%",
    flex: 1,
    backgroundColor: "transparent",
    paddingTop: "0.75rem",
    paddingBottom: "0.75rem",
    fontSize: "0.875rem",
    outline: "none",
    borderWidth: 0,
    color: colors.foreground,
    "::placeholder": { color: colors.mutedForeground },
  },
  list: {
    maxHeight: "300px",
    overflowX: "hidden",
    overflowY: "auto",
    scrollPaddingBlock: "0.25rem",
  },
  empty: {
    paddingBlock: "1.5rem",
    textAlign: "center",
    fontSize: "0.875rem",
    color: colors.mutedForeground,
  },
  group: {
    color: colors.foreground,
    overflow: "hidden",
    padding: "0.25rem",
  },
  groupHeading: {
    paddingInline: "0.5rem",
    paddingBlock: "0.375rem",
    fontSize: "0.75rem",
    fontWeight: 500,
    color: colors.mutedForeground,
  },
  separator: {
    marginInline: "-0.25rem",
    height: "1px",
    backgroundColor: colors.border,
  },
  item: {
    display: "flex",
    cursor: "default",
    alignItems: "center",
    gap: "0.5rem",
    borderRadius: "0.125rem",
    paddingInline: "0.5rem",
    paddingBlock: "0.375rem",
    fontSize: "0.875rem",
    outline: "none",
    userSelect: "none",
    position: "relative",
    transition: "background-color 0.1s ease, color 0.1s ease",
    backgroundColor: { default: "transparent", ":hover": colors.accent },
    color: { default: "inherit", ":hover": colors.accentForeground },
  },
  shortcut: {
    marginLeft: "auto",
    fontSize: "0.75rem",
    letterSpacing: "0.05em",
    color: colors.mutedForeground,
  },
  srOnly: {
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: 0,
    margin: "-1px",
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
});

