import * as stylex from "@stylexjs/stylex";

import { colors, radius } from "../../registry/bases/stylex/tokens.stylex";

export const styles = stylex.create({
  action: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.accent, default: colors.background },
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "0.8125rem",
    fontWeight: 500,
    gap: "0.375rem",
    height: "2.25rem",
    justifyContent: "center",
    paddingInline: "0.75rem",
    textDecorationLine: "none",
  },
  bar: (height: number, color: string) => ({
    backgroundColor: color,
    height,
  }),
  block: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: "0.75rem",
    overflow: "hidden",
    padding: "0.75rem",
  },
  blockFrame: {
    backgroundColor: colors.muted,
    borderRadius: radius.lg,
    borderWidth: 0,
    height: "32rem",
    width: "100%",
  },
  chart: {
    alignItems: "flex-end",
    display: "flex",
    gap: "0.625rem",
    height: "19rem",
    paddingBlockStart: "2rem",
  },
  chartBar: {
    borderRadius: radius.sm,
    flex: 1,
    minWidth: "0.5rem",
  },
  chartCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: "0.75rem",
    padding: { "@media (min-width: 640px)": "1.5rem", default: "1rem" },
  },
  colorButton: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "grid",
    fontSize: "0.6875rem",
    gap: "0.375rem",
    padding: 0,
    textAlign: "start",
  },
  colorGrid: {
    display: "grid",
    gap: "0.625rem",
    gridTemplateColumns: {
      "@media (min-width: 640px)": "repeat(10, minmax(0, 1fr))",
      default: "repeat(5, minmax(0, 1fr))",
    },
  },
  colorMeta: { color: colors.mutedForeground, fontFamily: "monospace" },
  colorSwatch: (color: string) => ({ backgroundColor: color }),
  colorTile: {
    borderColor: "color-mix(in oklab, currentColor 12%, transparent)",
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    height: "4.5rem",
    width: "100%",
  },
  empty: {
    alignItems: "center",
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderStyle: "dashed",
    borderWidth: 1,
    color: colors.mutedForeground,
    display: "flex",
    justifyContent: "center",
    minHeight: "18rem",
  },
  exampleFrame: {
    backgroundColor: colors.muted,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderStyle: "solid",
    borderWidth: 1,
    height: "calc(100svh - 10rem)",
    minHeight: "36rem",
    width: "100%",
  },
  grid: {
    display: "grid",
    gap: "1.5rem",
    gridTemplateColumns: {
      "@media (min-width: 1100px)": "repeat(2, minmax(0, 1fr))",
      default: "1fr",
    },
  },
  header: {
    alignItems: {
      "@media (min-width: 640px)": "center",
      default: "flex-start",
    },
    display: "flex",
    flexDirection: { "@media (min-width: 640px)": "row", default: "column" },
    gap: "1rem",
    justifyContent: "space-between",
  },
  nav: { display: "flex", flexWrap: "wrap", gap: "0.5rem" },
  page: {
    display: "grid",
    gap: { "@media (min-width: 768px)": "3rem", default: "2rem" },
    marginInline: "auto",
    maxWidth: "96rem",
    paddingBlock: { "@media (min-width: 768px)": "3rem", default: "2rem" },
    paddingInline: { "@media (min-width: 768px)": "1.5rem", default: "1rem" },
    width: "100%",
  },
  palette: { display: "grid", gap: "1rem" },
  row: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
    justifyContent: "space-between",
  },
  section: { display: "grid", gap: "1rem" },
  subtitle: {
    color: colors.mutedForeground,
    fontSize: "0.9375rem",
    lineHeight: 1.6,
    margin: 0,
    maxWidth: "44rem",
  },
  title: {
    color: colors.foreground,
    fontSize: { "@media (min-width: 768px)": "2.25rem", default: "1.875rem" },
    fontWeight: 700,
    letterSpacing: "-0.04em",
    margin: 0,
  },
  titleSmall: {
    color: colors.foreground,
    fontSize: "1rem",
    fontWeight: 600,
    margin: 0,
  },
});
