/* oxlint-disable sort-keys */
import * as stylex from "@stylexjs/stylex";

import { colors, radius } from "../../registry/bases/stylex/lib/tokens.stylex";

export const styles = stylex.create({
  action: {
    alignItems: "center",
    backgroundColor: {
      ":hover": "color-mix(in oklab, var(--primary) 88%, transparent)",
      default: colors.primary,
    },
    borderColor: "transparent",
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.primaryForeground,
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "0.8125rem",
    fontWeight: 500,
    gap: "0.375rem",
    height: "2.25rem",
    justifyContent: "center",
    paddingInline: "0.875rem",
    textDecorationLine: "none",
  },
  actionGhost: {
    backgroundColor: { ":hover": colors.accent, default: "transparent" },
    color: colors.foreground,
  },
  announcement: {
    alignItems: "center",
    backgroundColor: "color-mix(in oklab, var(--muted) 45%, transparent)",
    borderColor: colors.border,
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    display: "inline-flex",
    fontSize: "0.8125rem",
    fontWeight: 500,
    gap: "0.375rem",
    height: "1.875rem",
    paddingInline: "0.75rem",
    textDecorationLine: "none",
  },
  bar: (height: number, color: string) => ({
    backgroundColor: color,
    height,
  }),
  block: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 1px 2px color-mix(in oklab, black 5%, transparent)",
    display: "grid",
    overflow: "hidden",
  },
  blockBody: {
    alignItems: "flex-start",
    backgroundColor: colors.muted,
    display: "flex",
    justifyContent: "center",
    overflowX: "auto",
    padding: { default: "0.5rem", "@media (min-width: 768px)": 0 },
  },
  blockCode: {
    backgroundColor: colors.background,
    color: colors.foreground,
    fontFamily: "var(--font-geist-mono), ui-monospace, monospace",
    fontSize: "0.8125rem",
    lineHeight: 1.7,
    margin: 0,
    minHeight: "34rem",
    padding: "2rem",
    width: "100%",
  },
  blockFrame: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderStyle: "solid",
    borderWidth: 1,
    display: "block",
    height: { default: "34rem", "@media (min-width: 1024px)": "62.5rem" },
    width: "100%",
  },
  blockFrameWidth: (width: string) => ({ width }),
  blockHeader: {
    alignItems: "center",
    display: "flex",
    gap: "1rem",
    justifyContent: "space-between",
    minHeight: "3rem",
    paddingInline: "1rem",
  },
  blockHeaderLead: {
    alignItems: "center",
    display: "flex",
    gap: "1rem",
    minWidth: 0,
  },
  blockActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: "0.75rem",
  },
  blockTab: {
    backgroundColor: {
      "[data-active='true']": colors.background,
      default: "transparent",
    },
    borderColor: "transparent",
    borderRadius: radius.sm,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    cursor: "pointer",
    fontSize: "0.75rem",
    height: "1.75rem",
    paddingInline: "0.625rem",
  },
  blockTabs: {
    alignItems: "center",
    backgroundColor: colors.muted,
    borderRadius: radius.md,
    display: "flex",
    flexShrink: 0,
    gap: "0.125rem",
    padding: "0.1875rem",
  },
  blocksPage: {
    display: "flex",
    flexDirection: "column",
    gap: { default: "3rem", "@media (min-width: 768px)": "6rem" },
  },
  chart: {
    alignItems: "flex-end",
    display: "flex",
    gap: "0.625rem",
    height: "19rem",
    paddingBlockStart: "2rem",
  },
  chartBar: {
    borderRadius: radius.sm,
    flex: 1,
    minWidth: "0.5rem",
  },
  chartCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: "1.5rem",
    padding: { default: "1rem", "@media (min-width: 640px)": "1.5rem" },
  },
  chartCanvas: { height: "18rem", minWidth: 0, width: "100%" },
  chartCodeButton: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radius.sm,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    cursor: "pointer",
    fontSize: "0.75rem",
    height: "1.75rem",
    paddingInline: "0.625rem",
  },
  chartDisplay: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    overflow: "hidden",
  },
  chartFullWidth: {
    gridColumn: {
      default: "auto",
      "@media (min-width: 768px)": "span 2",
      "@media (min-width: 1024px)": "span 3",
    },
  },
  chartToolbar: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    minHeight: "3rem",
    paddingInline: "0.75rem",
  },
  chartsGrid: {
    display: "grid",
    gap: {
      default: "2.5rem",
      "@media (min-width: 768px)": "1.5rem",
      "@media (min-width: 1280px)": "2.5rem",
    },
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 768px)": "repeat(2, minmax(0, 1fr))",
      "@media (min-width: 1024px)": "repeat(3, minmax(0, 1fr))",
    },
    paddingBlock: "1.5rem",
  },
  colorButton: {
    alignItems: "center",
    aspectRatio: { default: "3 / 1", "@media (min-width: 640px)": "2 / 3" },
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "grid",
    fontSize: "0.6875rem",
    gap: "0.375rem",
    minWidth: 0,
    padding: 0,
    textAlign: "center",
  },
  colorGrid: {
    display: "grid",
    gap: "0.5rem",
    gridTemplateColumns: {
      default: "repeat(3, minmax(0, 1fr))",
      "@media (min-width: 640px)": "repeat(6, minmax(0, 1fr))",
      "@media (min-width: 1024px)": "repeat(11, minmax(0, 1fr))",
    },
  },
  colorMeta: {
    color: colors.mutedForeground,
    fontFamily: "var(--font-geist-mono), ui-monospace, monospace",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  colorLabel: {
    color: colors.mutedForeground,
    fontFamily: "var(--font-geist-mono), ui-monospace, monospace",
    fontSize: "0.75rem",
    fontVariantNumeric: "tabular-nums",
  },
  colorSwatch: (color: string) => ({ backgroundColor: color }),
  colorTile: {
    borderColor: "color-mix(in oklab, currentColor 12%, transparent)",
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    flex: 1,
    width: "100%",
  },
  content: {
    marginInline: "auto",
    maxWidth: "96rem",
    paddingBlockEnd: "1.5rem",
    paddingInline: { default: "1rem", "@media (min-width: 768px)": "1.5rem" },
    width: "100%",
  },
  contentBlocks: {
    paddingBlock: { default: "1rem", "@media (min-width: 768px)": "2.25rem" },
    paddingInline: { default: "1rem", "@media (min-width: 768px)": "3.25rem" },
  },
  contentSoft: {
    backgroundColor: "color-mix(in oklab, var(--muted) 38%, var(--background))",
    borderTopColor: colors.border,
    borderTopStyle: "solid",
    borderTopWidth: 1,
  },
  empty: {
    alignItems: "center",
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderStyle: "dashed",
    borderWidth: 1,
    color: colors.mutedForeground,
    display: "flex",
    justifyContent: "center",
    minHeight: "18rem",
  },
  exampleFrame: {
    backgroundColor: colors.background,
    borderWidth: 0,
    display: "block",
    height: { default: "42rem", "@media (min-width: 1024px)": "52rem" },
    width: "100%",
  },
  exampleShell: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: {
      default: radius.lg,
      "@media (min-width: 1280px)": radius.xl,
    },
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
  },
  formatSelect: {
    appearance: "none",
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    cursor: "pointer",
    fontSize: "0.8125rem",
    fontWeight: 500,
    height: "2rem",
    paddingInline: "0.75rem",
    width: "8.375rem",
  },
  hero: {
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
  },
  heroActions: {
    alignItems: "center",
    display: "flex",
    gap: "0.5rem",
    justifyContent: "center",
    paddingTop: "0.5rem",
    width: "100%",
  },
  heroDescription: {
    color: colors.foreground,
    fontSize: { default: "1rem", "@media (min-width: 640px)": "1.125rem" },
    lineHeight: 1.55,
    margin: 0,
    maxWidth: "56rem",
    textAlign: "center",
    textWrap: "balance",
  },
  heroInner: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: { default: "0.5rem", "@media (min-width: 1280px)": "1rem" },
    marginInline: "auto",
    maxWidth: "96rem",
    paddingBlock: {
      default: "2rem",
      "@media (min-width: 768px)": "4rem",
      "@media (min-width: 1024px)": "5rem",
    },
    paddingInline: "1.5rem",
    textAlign: "center",
  },
  heroTitle: {
    color: colors.foreground,
    fontSize: {
      default: "1.875rem",
      "@media (min-width: 1280px)": "3rem",
    },
    fontWeight: 600,
    letterSpacing: "-0.045em",
    lineHeight: 1.1,
    margin: 0,
    maxWidth: "56rem",
    textWrap: "balance",
  },
  nav: {
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    scrollMarginTop: "6rem",
  },
  navCta: {
    display: { default: "none", "@media (min-width: 1024px)": "inline-flex" },
    marginInlineStart: "auto",
  },
  navInner: {
    alignItems: "center",
    display: "flex",
    gap: "0.25rem",
    marginInline: "auto",
    maxWidth: "96rem",
    overflowX: "auto",
    paddingBlock: "1rem",
    paddingInline: { default: 0, "@media (min-width: 768px)": "1.5rem" },
    scrollbarWidth: "none",
  },
  navLink: {
    alignItems: "center",
    color: {
      ":hover": colors.foreground,
      "[data-active='true']": colors.foreground,
      default: colors.mutedForeground,
    },
    display: "inline-flex",
    flexShrink: 0,
    fontSize: "1rem",
    fontWeight: 500,
    height: "1.75rem",
    justifyContent: "center",
    paddingInline: "1rem",
    textDecorationLine: "none",
    transitionDuration: "150ms",
    transitionProperty: "color",
  },
  palette: {
    display: "grid",
    gap: "1rem",
  },
  paletteHeader: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    paddingInline: "1rem",
  },
  paletteTitle: {
    color: colors.foreground,
    fontSize: "0.875rem",
    fontWeight: 500,
    margin: 0,
    paddingInlineStart: "0.25rem",
    textTransform: "capitalize",
  },
  palettes: {
    display: "grid",
    gap: { default: "2rem", "@media (min-width: 1024px)": "4rem" },
  },
  row: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
    justifyContent: "space-between",
  },
  section: {
    display: "grid",
    gap: "1rem",
  },
  subtitle: {
    color: colors.mutedForeground,
    fontSize: "0.8125rem",
    lineHeight: 1.6,
    margin: 0,
  },
  titleSmall: {
    color: colors.foreground,
    fontSize: "1rem",
    fontWeight: 600,
    margin: 0,
    textTransform: "capitalize",
  },
  viewportButton: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      "[data-active='true']": colors.accent,
      ":hover": colors.accent,
    },
    borderRadius: radius.sm,
    borderWidth: 0,
    color: colors.foreground,
    cursor: "pointer",
    display: "flex",
    height: "1.75rem",
    justifyContent: "center",
    textDecoration: "none",
    width: "1.75rem",
  },
  viewportControls: {
    alignItems: "center",
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    display: { default: "none", "@media (min-width: 1024px)": "flex" },
    gap: "0.0625rem",
    padding: "0.125rem",
  },
});
