import * as stylex from "@stylexjs/stylex";

import { colors, radius } from "../tokens.stylex";

export const styles = stylex.create({
  backdrop: {
    backgroundColor: "color-mix(in oklab, black 80%, transparent)",
    inset: 0,
    opacity: 1,
    position: "fixed",
    transition: "opacity 0.15s ease-in-out",
    zIndex: 50,
  },
  backdropHidden: {
    opacity: 0,
  },
  closeButton: {
    alignItems: "center",
    background: "none",
    borderRadius: radius.sm,
    borderWidth: 0,
    boxShadow: {
      ":focus-visible": `0 0 0 2px color-mix(in oklab, ${colors.ring} 50%, transparent)`,
      default: null,
    },
    color: colors.foreground,
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    opacity: { ":hover": 1, default: 0.7 },
    outline: "none",
    padding: "0.25rem",
    position: "absolute",
    right: "1rem",
    top: "1rem",
    transition: "opacity 0.15s ease-in-out",
  },
  description: {
    color: colors.mutedForeground,
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
  },
  footer: {
    display: "flex",
    flexDirection: "column-reverse",
    gap: "0.5rem",
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    textAlign: "center",
  },
  popup: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow:
      "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
    color: colors.foreground,
    display: "grid",
    gap: "1rem",
    left: "50%",
    maxWidth: {
      "@media (min-width: 640px)": "32rem",
      default: "calc(100% - 2rem)",
    },
    opacity: 1,
    outline: "none",
    padding: "1.5rem",
    position: "fixed",
    top: "50%",
    transform: "translate(-50%, -50%) scale(1)",
    transition: "opacity 0.2s ease-in-out, transform 0.2s ease-in-out",
    width: "100%",
    zIndex: 50,
  },
  popupHidden: {
    opacity: 0,
    transform: "translate(-50%, -50%) scale(0.95)",
  },
  srOnly: {
    borderWidth: 0,
    clip: "rect(0, 0, 0, 0)",
    height: "1px",
    margin: "-1px",
    overflow: "hidden",
    padding: 0,
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
  title: {
    color: colors.foreground,
    fontSize: "1.125rem",
    fontWeight: 600,
    letterSpacing: "-0.025em",
    lineHeight: 1,
  },
});
