export const ROUTES = {
  AGENT_SKILLS_INDEX: "/.well-known/agent-skills/index.json",
  AGENT_SKILLS_SITE_SKILL: "/.well-known/agent-skills/site-skill.md",
  API_CATALOG: "/.well-known/api-catalog",
  API_STATUS: "/api/status",
  DOCS: "/docs",
  DOCS_CHANGELOG: "/docs/changelog",
  DOCS_COMPONENTS: "/docs/components",
  DOCS_INSTALLATION: "/docs/installation",
  DOCS_INSTALLATION_STYLEX: "/docs/installation/stylex",
  DOCS_INSTALLATION_STYLEX_ASTRO: "/docs/installation/stylex/astro",
  DOCS_INSTALLATION_STYLEX_LARAVEL: "/docs/installation/stylex/laravel",
  DOCS_INSTALLATION_STYLEX_MANUAL: "/docs/installation/stylex/manual",
  DOCS_INSTALLATION_STYLEX_NEXT: "/docs/installation/stylex/next",
  DOCS_INSTALLATION_STYLEX_REACT_ROUTER:
    "/docs/installation/stylex/react-router",
  DOCS_INSTALLATION_STYLEX_TANSTACK_START:
    "/docs/installation/stylex/tanstack-start",
  DOCS_INSTALLATION_STYLEX_VITE: "/docs/installation/stylex/vite",
  DOCS_MCP: "/docs/mcp",
  DOCS_REGISTRY: "/docs/registry",
  DOCS_RTL: "/docs/rtl",
  DOCS_THEMING: "/docs/theming",
  HOME: "/",
  LLMS: "/llms.txt",
  LLMS_FULL: "/llms-full.txt",
  LLMS_MD: "/llms.md",
  MANIFEST: "/manifest.webmanifest",
  MCP: "/mcp",
  OG: "/og",
  OPENAPI: "/openapi.json",
  REGISTRY: "/r/registry.json",
  ROBOTS: "/robots.txt",
  RSS: "/rss.xml",
  SITEMAP: "/sitemap.xml",
  SPONSOR: "/sponsor",
} as const;
