import * as stylex from "@stylexjs/stylex";
import { colors, radius } from "../tokens.stylex";

export const styles = stylex.create({
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 50,
    backgroundColor: "color-mix(in oklab, black 80%, transparent)",
    opacity: 1,
    transition: "opacity 0.3s ease-in-out",
  },
  backdropHidden: { opacity: 0 },
  content: {
    position: "fixed",
    zIndex: 50,
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    backgroundColor: colors.background,
    outline: "none",
    transition: "transform 0.3s ease-in-out",
  },
  right: {
    insetBlock: 0,
    right: 0,
    height: "100%",
    width: "75%",
    maxWidth: "24rem",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: colors.border,
    transform: "translateX(0)",
  },
  rightHidden: { transform: "translateX(100%)" },
  left: {
    insetBlock: 0,
    left: 0,
    height: "100%",
    width: "75%",
    maxWidth: "24rem",
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: colors.border,
    transform: "translateX(0)",
  },
  leftHidden: { transform: "translateX(-100%)" },
  top: {
    insetInline: 0,
    top: 0,
    width: "100%",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    transform: "translateY(0)",
  },
  topHidden: { transform: "translateY(-100%)" },
  bottom: {
    insetInline: 0,
    bottom: 0,
    width: "100%",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    transform: "translateY(0)",
  },
  bottomHidden: { transform: "translateY(100%)" },
  closeButton: {
    position: "absolute",
    top: "1rem",
    right: "1rem",
    borderRadius: radius.sm,
    opacity: { default: 0.7, ":hover": 1 },
    transition: "opacity 0.15s ease-in-out",
    outline: "none",
    borderWidth: 0,
    background: "none",
    cursor: "pointer",
    padding: "0.25rem",
    color: colors.foreground,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: {
      default: null,
      ":focus-visible":
        `0 0 0 2px color-mix(in oklab, ${colors.ring} 50%, transparent)`,
    },
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
    padding: "1rem",
  },
  footer: {
    marginTop: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    padding: "1rem",
  },
  title: { color: colors.foreground, fontWeight: 600 },
  description: { fontSize: "0.875rem", color: colors.mutedForeground },
  srOnly: {
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: 0,
    margin: "-1px",
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
});

