import {
  BASE_COLORS,
  BASES,
  DEFAULT_CREATE_CONFIG,
  FONTS,
  ICON_LIBRARIES,
  MENU_ACCENTS,
  MENU_COLORS,
  RADII,
  STYLES,
  TEMPLATES,
  THEMES,
} from "@/app/(app)/(create)/lib/config";
import type {
  BaseColorValue,
  BaseValue,
  FontValue,
  IconLibraryValue,
  MenuAccentValue,
  MenuColorValue,
  RadiusValue,
  StyleValue,
  TemplateValue,
  ThemeValue,
} from "@/app/(app)/(create)/lib/config";

interface ServerCreateConfig {
  base: BaseValue;
  baseColor: BaseColorValue;
  chartColor: ThemeValue;
  font: FontValue;
  fontHeading: "inherit" | FontValue;
  iconLibrary: IconLibraryValue;
  item: string;
  menuAccent: MenuAccentValue;
  menuColor: MenuColorValue;
  pointer: boolean;
  radius: RadiusValue;
  rtl: boolean;
  size: number;
  style: StyleValue;
  template: TemplateValue;
  theme: ThemeValue;
}

const optionValues = {
  base: BASES,
  baseColor: BASE_COLORS,
  chartColor: THEMES,
  font: FONTS,
  iconLibrary: ICON_LIBRARIES,
  menuAccent: MENU_ACCENTS,
  menuColor: MENU_COLORS,
  radius: RADII,
  style: STYLES,
  template: TEMPLATES,
  theme: THEMES,
} as const;

function decodePreset(value: string): Record<string, unknown> {
  try {
    const normalized = value.replaceAll("-", "+").replaceAll("_", "/");
    const padded = normalized.padEnd(
      normalized.length + ((4 - (normalized.length % 4)) % 4),
      "="
    );
    const parsed: unknown = JSON.parse(atob(padded));
    return parsed && typeof parsed === "object" && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : {};
  } catch {
    return {};
  }
}

export function parseServerCreateConfig(searchParams: URLSearchParams) {
  const preset = searchParams.get("preset");
  const source: Record<string, unknown> = preset
    ? decodePreset(preset)
    : Object.fromEntries(searchParams);
  const config: Record<string, string | boolean | number> = {
    ...DEFAULT_CREATE_CONFIG,
  };

  for (const [key, options] of Object.entries(optionValues)) {
    const value = source[key];
    if (
      typeof value === "string" &&
      options.some((option) => option.value === value)
    ) {
      config[key] = value;
    }
  }

  const heading = source.fontHeading;
  if (
    heading === "inherit" ||
    (typeof heading === "string" &&
      FONTS.some((font) => font.value === heading))
  ) {
    config.fontHeading = heading;
  }

  for (const key of ["pointer", "rtl"] as const) {
    const value = source[key];
    config[key] = value === true || value === "true" || value === "1";
  }

  const size = Number(source.size);
  if (Number.isFinite(size)) {
    config.size = Math.min(120, Math.max(65, size));
  }

  return config as unknown as ServerCreateConfig;
}

const colorMap = {
  blue: "#2563eb",
  green: "#16a34a",
  neutral: "#171717",
  orange: "#ea580c",
  red: "#dc2626",
  rose: "#e11d48",
  violet: "#7c3aed",
  yellow: "#ca8a04",
} as const;

export function buildStyleXPreset(config: ServerCreateConfig, origin: string) {
  const font = FONTS.find((item) => item.value === config.font) ?? FONTS[0];
  const heading =
    config.fontHeading === "inherit"
      ? font
      : (FONTS.find((item) => item.value === config.fontHeading) ?? font);
  const selectedRadius =
    RADII.find((item) => item.value === config.radius) ?? RADII[0];
  const primary = colorMap[config.theme];

  return {
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    cssVars: {
      dark: {
        accent: "oklch(0.269 0 0)",
        background: "oklch(0.145 0 0)",
        border: "oklch(1 0 0 / 10%)",
        foreground: "oklch(0.985 0 0)",
        primary,
        "primary-foreground": "#ffffff",
      },
      light: {
        accent: "oklch(0.97 0 0)",
        background: "oklch(1 0 0)",
        border: "oklch(0.922 0 0)",
        foreground: "oklch(0.145 0 0)",
        primary,
        "primary-foreground": "#ffffff",
      },
      theme: {
        "font-heading": heading.family,
        "font-sans": font.family,
        radius: selectedRadius.radius,
      },
    },
    dependencies: ["@stylexjs/stylex", "lucide-react"],
    description: `A ${config.style} StyleX design system using ${config.base === "base" ? "Base UI" : "Radix"}.`,
    meta: config,
    name: "stylex-design-system",
    registryDependencies: [`${origin}/r/stylex-tokens.json`],
    title: "StyleX Design System",
    type: "registry:style",
  };
}

export function buildStyleXInstructions(
  config: ServerCreateConfig,
  origin: string
) {
  const presetUrl = new URL("/create/init", origin);
  for (const [key, value] of Object.entries(config)) {
    presetUrl.searchParams.set(key, String(value));
  }

  return `# Install the StyleX design system

This preset was generated by shadcn-cssinjs Create.

## New project

\`\`\`bash
pnpm dlx shadcn-cssinjs@latest init --template ${config.template} --preset '${presetUrl}'${config.rtl ? " --rtl" : ""}${config.pointer ? " --pointer" : ""}
\`\`\`

## Existing project

\`\`\`bash
pnpm dlx shadcn-cssinjs@latest add '${presetUrl}'
\`\`\`

The CLI installs the StyleX Babel/PostCSS integration, shared tokens, and the selected component base automatically.
`;
}
