import * as stylex from "@stylexjs/stylex";

import { colors, radius } from "../tokens.stylex";

export const styles = stylex.create({
  chip: {
    alignItems: "center",
    backgroundColor: colors.secondary,
    borderRadius: radius.sm,
    color: colors.secondaryForeground,
    display: "inline-flex",
    fontSize: "0.75rem",
    gap: "0.25rem",
    height: "1.375rem",
    paddingInlineEnd: "0.25rem",
    paddingInlineStart: "0.5rem",
  },
  chipRemove: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.accent, default: "transparent" },
    border: 0,
    borderRadius: radius.sm,
    color: colors.mutedForeground,
    cursor: "pointer",
    display: "inline-flex",
    height: "1rem",
    justifyContent: "center",
    padding: 0,
    width: "1rem",
  },
  chips: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: {
      ":focus-within": colors.ring,
      default: colors.input,
    },
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: "1px",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.25rem",
    minHeight: "2.25rem",
    paddingBlock: "0.25rem",
    paddingInline: "0.5rem",
    width: "100%",
  },
  chipsInput: {
    backgroundColor: "transparent",
    border: 0,
    color: colors.foreground,
    flex: 1,
    fontSize: "0.875rem",
    minWidth: "4rem",
    outline: "none",
  },
  clear: {
    alignItems: "center",
    backgroundColor: "transparent",
    border: 0,
    color: colors.mutedForeground,
    cursor: "pointer",
    display: "inline-flex",
    insetInlineEnd: "0.5rem",
    justifyContent: "center",
    padding: 0,
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
  },
  content: {
    backgroundColor: colors.popover,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow:
      "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
    color: colors.popoverForeground,
    maxHeight: "min(var(--available-height), 20rem)",
    minWidth: "var(--anchor-width)",
    opacity: 1,
    outline: "none",
    overflowY: "auto",
    padding: "0.25rem",
    transformOrigin: "var(--transform-origin)",
    transition: "opacity 0.15s ease-in-out",
    width: "var(--anchor-width)",
    zIndex: 50,
  },
  contentHidden: { opacity: 0 },
  empty: {
    color: colors.mutedForeground,
    fontSize: "0.875rem",
    paddingBlock: "1.5rem",
    textAlign: "center",
  },
  groupLabel: {
    color: colors.mutedForeground,
    fontSize: "0.75rem",
    fontWeight: 500,
    paddingBlock: "0.375rem",
    paddingInline: "0.5rem",
  },
  input: {
    "::placeholder": { color: colors.mutedForeground },
    backgroundColor: "transparent",
    borderColor: {
      ":focus-visible": colors.ring,
      default: colors.input,
    },
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: {
      ":focus-visible": `0 0 0 3px color-mix(in oklab, ${colors.ring} 50%, transparent)`,
      default: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    },
    color: colors.foreground,
    fontSize: "0.875rem",
    height: "2.25rem",
    outline: "none",
    paddingInlineEnd: "2rem",
    paddingInlineStart: "0.75rem",
    width: "100%",
  },
  inputWrap: {
    position: "relative",
    width: "100%",
  },
  item: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: radius.sm,
    color: colors.popoverForeground,
    cursor: "default",
    display: "flex",
    fontSize: "0.875rem",
    gap: "0.5rem",
    outline: "none",
    paddingBlock: "0.375rem",
    paddingInlineEnd: "2rem",
    paddingInlineStart: "0.5rem",
    position: "relative",
    userSelect: "none",
  },
  itemHighlighted: {
    backgroundColor: colors.accent,
    color: colors.accentForeground,
  },
  itemIndicator: {
    alignItems: "center",
    display: "flex",
    height: "0.875rem",
    insetInlineEnd: "0.5rem",
    justifyContent: "center",
    position: "absolute",
    width: "0.875rem",
  },
  list: {
    overflowY: "auto",
  },
  trigger: {
    alignItems: "center",
    backgroundColor: "transparent",
    border: 0,
    color: colors.mutedForeground,
    cursor: "pointer",
    display: "inline-flex",
    insetInlineEnd: "0.5rem",
    justifyContent: "center",
    padding: 0,
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
  },
});
