import * as stylex from "@stylexjs/stylex";

import { colors, radius } from "../tokens.stylex";

export const styles = stylex.create({
  backdrop: {
    backgroundColor: "color-mix(in oklab, black 80%, transparent)",
    inset: 0,
    opacity: 1,
    position: "fixed",
    transition: "opacity 0.3s ease-in-out",
    zIndex: 50,
  },
  backdropHidden: { opacity: 0 },
  bottom: {
    borderTopColor: colors.border,
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    bottom: 0,
    insetInline: 0,
    transform: "translateY(0)",
    width: "100%",
  },
  bottomHidden: { transform: "translateY(100%)" },
  closeButton: {
    alignItems: "center",
    background: "none",
    borderRadius: radius.sm,
    borderWidth: 0,
    boxShadow: {
      ":focus-visible": `0 0 0 2px color-mix(in oklab, ${colors.ring} 50%, transparent)`,
      default: null,
    },
    color: colors.foreground,
    cursor: "pointer",
    display: "flex",
    insetInlineEnd: "1rem",
    justifyContent: "center",
    opacity: { ":hover": 1, default: 0.7 },
    outline: "none",
    padding: "0.25rem",
    position: "absolute",
    top: "1rem",
    transition: "opacity 0.15s ease-in-out",
  },
  content: {
    backgroundColor: colors.background,
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    outline: "none",
    position: "fixed",
    transition: "transform 0.3s ease-in-out",
    zIndex: 50,
  },
  description: { color: colors.mutedForeground, fontSize: "0.875rem" },
  footer: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    marginTop: "auto",
    padding: "1rem",
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
    padding: "1rem",
  },
  left: {
    borderRightColor: colors.border,
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    height: "100%",
    insetBlock: 0,
    left: 0,
    maxWidth: "24rem",
    transform: "translateX(0)",
    width: "75%",
  },
  leftHidden: { transform: "translateX(-100%)" },
  right: {
    borderLeftColor: colors.border,
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    height: "100%",
    insetBlock: 0,
    maxWidth: "24rem",
    right: 0,
    transform: "translateX(0)",
    width: "75%",
  },
  rightHidden: { transform: "translateX(100%)" },
  srOnly: {
    borderWidth: 0,
    clip: "rect(0, 0, 0, 0)",
    height: "1px",
    margin: "-1px",
    overflow: "hidden",
    padding: 0,
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
  title: { color: colors.foreground, fontWeight: 600 },
  top: {
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    insetInline: 0,
    top: 0,
    transform: "translateY(0)",
    width: "100%",
  },
  topHidden: { transform: "translateY(-100%)" },
});
