/* oxlint-disable sort-keys */
import * as stylex from "@stylexjs/stylex";

import {
  colors,
  radius,
} from "../../../../registry/bases/stylex/lib/tokens.stylex";

const pulse = stylex.keyframes({
  "0%, 100%": { opacity: 0.55 },
  "50%": { opacity: 1 },
});

export const typesetStyles = stylex.create({
  actionRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  button: {
    alignItems: "center",
    backgroundColor: {
      ":disabled": colors.muted,
      ":hover": colors.accent,
      default: colors.secondary,
    },
    borderColor: "transparent",
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: {
      ":disabled": colors.mutedForeground,
      default: colors.secondaryForeground,
    },
    cursor: { ":disabled": "not-allowed", default: "pointer" },
    display: "inline-flex",
    fontSize: "0.8125rem",
    fontWeight: 500,
    gap: "0.375rem",
    height: "2.25rem",
    justifyContent: "center",
    outlineColor: { ":focus-visible": colors.ring, default: "transparent" },
    outlineOffset: 2,
    outlineStyle: "solid",
    outlineWidth: { ":focus-visible": 2, default: 0 },
    paddingInline: "0.75rem",
    transitionDuration: "150ms",
    transitionProperty: "background-color, color, opacity",
  },
  buttonPrimary: {
    backgroundColor: { ":hover": colors.accent, default: "transparent" },
    borderColor: colors.border,
    color: colors.foreground,
  },
  cardContent: {
    display: "flex",
    flex: 1,
    minHeight: 0,
    overflowX: { default: "auto", "@media (min-width: 768px)": "hidden" },
    overflowY: { default: "hidden", "@media (min-width: 768px)": "auto" },
    padding: "0.6875rem",
  },
  cardFooter: {
    borderColor: colors.border,
    borderStyle: "solid",
    borderTopWidth: 1,
    borderWidth: 0,
    display: "flex",
    flexDirection: {
      default: "row-reverse",
      "@media (min-width: 768px)": "column",
    },
    gap: "0.5rem",
    minWidth: 0,
    padding: "0.75rem",
  },
  cardHeader: {
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: colors.border,
    borderStyle: "solid",
    borderWidth: 0,
    display: { default: "none", "@media (min-width: 768px)": "flex" },
    justifyContent: "space-between",
    minHeight: "3rem",
    paddingInline: "0.75rem",
  },
  code: {
    backgroundColor: colors.muted,
    borderRadius: radius.md,
    color: colors.foreground,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "0.75rem",
    lineHeight: 1.65,
    margin: 0,
    maxHeight: "25.5rem",
    overflow: "auto",
    padding: "0.75rem",
    whiteSpace: "pre-wrap",
  },
  control: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flex: { default: "0 0 10.5rem", "@media (min-width: 768px)": "none" },
    height: "3.5rem",
    minWidth: 0,
    overflow: "hidden",
    position: "relative",
  },
  controlContent: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    minWidth: 0,
    paddingInlineEnd: "2.5rem",
    paddingInlineStart: "0.625rem",
  },
  controlIcon: {
    alignItems: "center",
    color: colors.foreground,
    display: "flex",
    height: "1.125rem",
    justifyContent: "center",
    pointerEvents: "none",
    position: "absolute",
    right: "0.625rem",
    top: "50%",
    transform: "translateY(-50%)",
    width: "1.125rem",
  },
  controlGrid: {
    display: "flex",
    flexDirection: { default: "row", "@media (min-width: 768px)": "column" },
    gap: { default: "0.625rem", "@media (min-width: 768px)": "0.8125rem" },
    minWidth: "max-content",
    width: "100%",
  },
  controlLabel: {
    color: colors.mutedForeground,
    fontSize: "0.75rem",
    fontWeight: 400,
    letterSpacing: "0.01em",
  },
  controlSelect: {
    appearance: "none",
    backgroundColor: "transparent",
    borderWidth: 0,
    cursor: "pointer",
    inset: 0,
    opacity: 0,
    outlineColor: { ":focus-visible": colors.ring, default: "transparent" },
    outlineOffset: -2,
    outlineStyle: "solid",
    outlineWidth: { ":focus-visible": 1, default: 0 },
    position: "absolute",
    zIndex: 1,
  },
  controlValue: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  customizer: {
    alignSelf: "flex-start",
    backdropFilter: "blur(20px)",
    backgroundColor: colors.card,
    borderRadius: "1rem",
    boxShadow:
      "0 0 0 1px color-mix(in oklab, var(--foreground) 10%, transparent)",
    color: colors.foreground,
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    maxHeight: "100%",
    minHeight: 0,
    overflow: "hidden",
    width: {
      default: "100%",
      "@media (min-width: 768px)": "12rem",
      "@media (min-width: 1536px)": "14rem",
    },
    zIndex: 10,
  },
  designer: {
    alignItems: "flex-start",
    display: "flex",
    flex: 1,
    flexDirection: {
      default: "column",
      "@media (min-width: 768px)": "row-reverse",
    },
    gap: { default: "1rem", "@media (min-width: 768px)": "1.5rem" },
    minHeight: 0,
    paddingBlockEnd: { default: "1rem", "@media (min-width: 768px)": "1.5rem" },
    paddingInline: { default: "1rem", "@media (min-width: 768px)": "1.5rem" },
    paddingTop: { default: "0.25rem", "@media (min-width: 768px)": "0.375rem" },
  },
  dialog: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: "1rem",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 24px 80px color-mix(in oklab, black 35%, transparent)",
    display: "grid",
    gap: "1rem",
    maxHeight: "85svh",
    maxWidth: "46rem",
    overflow: "auto",
    padding: "1rem",
    width: "calc(100% - 2rem)",
  },
  dialogClose: {
    position: "absolute",
    right: "0.75rem",
    top: "0.75rem",
  },
  dialogOverlay: {
    alignItems: "center",
    backgroundColor: "color-mix(in oklab, black 50%, transparent)",
    display: "flex",
    inset: 0,
    justifyContent: "center",
    position: "fixed",
    zIndex: 100,
  },
  docsBody: {
    display: "grid",
    flex: 1,
    gap: "1rem",
    minHeight: 0,
    overflowY: "auto",
    padding: "1rem",
  },
  docsButton: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.accent, default: colors.background },
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "0.75rem",
    fontWeight: 500,
    gap: "0.375rem",
    height: "2rem",
    paddingInline: "0.625rem",
    width: "fit-content",
  },
  docsCodeWrap: { position: "relative" },
  docsColumn: {
    alignItems: "flex-start",
    display: { default: "none", "@media (min-width: 1280px)": "flex" },
    flexDirection: "column",
    flexShrink: 0,
    gap: "0.75rem",
    width: {
      default: "22rem",
      "@media (min-width: 1536px)": "26rem",
    },
  },
  docsContent: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: 0,
  },
  docsFrameworkSelect: {
    appearance: "auto",
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    cursor: "pointer",
    fontSize: "0.75rem",
    height: "2rem",
    paddingInline: "0.625rem",
  },
  docsCopy: {
    position: "absolute",
    right: "0.5rem",
    top: "0.5rem",
  },
  docsHeader: {
    alignItems: "center",
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    justifyContent: "space-between",
    paddingBlock: "0.75rem",
    paddingInline: "1rem",
  },
  docsPanel: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: "1rem",
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    maxHeight: "calc(100svh - 16rem)",
    overflow: "hidden",
    width: "100%",
  },
  docsLink: {
    color: { ":hover": colors.foreground, default: colors.mutedForeground },
    fontSize: "0.75rem",
    paddingInline: "0.75rem",
    textDecorationLine: "none",
  },
  docsScroll: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: "1.5rem",
    minHeight: 0,
    overflowY: "auto",
    padding: { default: "1rem", "@media (min-width: 768px)": "1.5rem" },
  },
  docsSection: { display: "grid", gap: "0.625rem" },
  docsText: {
    color: colors.mutedForeground,
    fontSize: "0.8125rem",
    lineHeight: 1.65,
    margin: 0,
  },
  docsToolbar: {
    alignItems: "center",
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: "0.5rem",
    justifyContent: "space-between",
    paddingBlock: "0.75rem",
    paddingInline: "1rem",
  },
  docsTitle: {
    color: colors.foreground,
    fontSize: "0.875rem",
    fontWeight: 600,
    margin: 0,
  },
  fieldSeparator: {
    backgroundColor: colors.border,
    display: { default: "none", "@media (min-width: 768px)": "block" },
    height: 1,
    width: "100%",
  },
  getCodeButton: {
    display: { default: "inline-flex", "@media (min-width: 1280px)": "none" },
  },
  icon: { height: "1rem", width: "1rem" },
  iconButton: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.accent, default: "transparent" },
    borderColor: "transparent",
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: { ":hover": colors.foreground, default: colors.mutedForeground },
    cursor: { ":disabled": "not-allowed", default: "pointer" },
    display: "inline-flex",
    height: "2rem",
    justifyContent: "center",
    opacity: { ":disabled": 0.4, default: 1 },
    outlineColor: { ":focus-visible": colors.ring, default: "transparent" },
    outlineOffset: 2,
    outlineStyle: "solid",
    outlineWidth: { ":focus-visible": 2, default: 0 },
    padding: 0,
    width: "2rem",
  },
  lockButton: {
    opacity: { default: 0, "[data-locked='true']": 1, ":focus-within": 1 },
    position: "absolute",
    right: "1.875rem",
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 3,
  },
  menuIcon: { height: "1.25rem", width: "1.25rem" },
  menu: { alignItems: "center", display: "flex", gap: "0.25rem" },
  menuItem: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.accent, default: "transparent" },
    borderColor: "transparent",
    borderRadius: radius.sm,
    borderStyle: "solid",
    borderWidth: 0,
    color: colors.foreground,
    cursor: { ":disabled": "not-allowed", default: "pointer" },
    display: "flex",
    fontSize: "0.8125rem",
    gap: "0.5rem",
    height: "2rem",
    opacity: { ":disabled": 0.45, default: 1 },
    paddingInline: "0.5rem",
    textAlign: "left",
    width: "100%",
  },
  menuPopover: {
    backgroundColor: colors.popover,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 12px 32px color-mix(in oklab, black 24%, transparent)",
    display: "grid",
    gap: "0.125rem",
    left: "calc(100% + 0.75rem)",
    minWidth: "10rem",
    padding: "0.375rem",
    position: "absolute",
    top: 0,
    zIndex: 80,
  },
  menuRoot: { position: "relative", width: "100%" },
  menuSeparator: {
    backgroundColor: colors.border,
    height: 1,
    marginBlock: "0.25rem",
  },
  menuTrigger: {
    alignItems: "center",
    backgroundColor: { ":hover": colors.accent, default: "transparent" },
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.foreground,
    cursor: "pointer",
    display: "flex",
    fontSize: "0.875rem",
    fontWeight: 500,
    height: "2.25rem",
    justifyContent: "space-between",
    paddingInline: "0.625rem",
    width: "100%",
  },
  preview: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: "1rem",
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flex: 1,
    height: "100%",
    isolation: "isolate",
    minHeight: { default: "30rem", "@media (min-width: 768px)": 0 },
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  previewFrame: { borderWidth: 0, height: "100%", width: "100%" },
  root: {
    backgroundColor: "color-mix(in oklab, var(--muted) 42%, var(--background))",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
    zIndex: 10,
  },
  skeleton: {
    animationDuration: "1.5s",
    animationIterationCount: "infinite",
    animationName: pulse,
    animationTimingFunction: "ease-in-out",
    backgroundColor: colors.muted,
  },
  tab: {
    backgroundColor: {
      "[data-active='true']": colors.accent,
      default: "transparent",
    },
    borderColor: "transparent",
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: {
      "[data-active='true']": colors.foreground,
      default: colors.mutedForeground,
    },
    cursor: "pointer",
    fontSize: "0.75rem",
    fontWeight: 500,
    height: "1.75rem",
    paddingInline: "0.625rem",
  },
  tabs: { alignItems: "center", display: "flex", gap: "0.25rem" },
  toolbar: {
    alignItems: "center",
    bottom: "0.75rem",
    display: "flex",
    gap: "0.375rem",
    left: "50%",
    position: "absolute",
    transform: "translateX(-50%)",
    zIndex: 20,
  },
  toolbarGroup: {
    alignItems: "center",
    backdropFilter: "blur(20px)",
    backgroundColor: "color-mix(in oklab, var(--card) 90%, transparent)",
    borderRadius: "0.75rem",
    boxShadow: "0 12px 32px color-mix(in oklab, black 28%, transparent)",
    color: colors.foreground,
    display: "flex",
    gap: "0.25rem",
    padding: "0.25rem",
  },
  toolbarLink: {
    alignItems: "center",
    borderRadius: "0.5rem",
    color: colors.mutedForeground,
    cursor: "pointer",
    display: "flex",
    fontSize: "0.75rem",
    fontWeight: 500,
    gap: "0.375rem",
    height: "1.75rem",
    paddingInline: "0.625rem",
    textDecoration: "none",
  },
  toolbarLinkIcon: {
    display: { default: "block", "@media (min-width: 768px)": "none" },
    height: "0.875rem",
    width: "0.875rem",
  },
  toolbarPill: {
    backgroundColor: {
      default: "transparent",
      "[data-active='true']": colors.accent,
    },
    borderRadius: "0.5rem",
    borderWidth: 0,
    color: {
      default: colors.mutedForeground,
      "[data-active='true']": colors.accentForeground,
    },
    cursor: "pointer",
    fontSize: "0.75rem",
    fontWeight: 500,
    height: "1.75rem",
    minWidth: "1.75rem",
    paddingInline: "0.5rem",
  },
});

export const previewStyles = stylex.create({
  afterHeading: { marginBlockStart: "1em" },
  blockquote: {
    borderColor: colors.border,
    borderInlineStartWidth: 2,
    borderStyle: "solid",
    marginBlockEnd: 0,
    marginBlockStart: "1.25em",
    marginInline: 0,
    paddingInlineStart: "1em",
  },
  chat: {
    display: "flex",
    flexDirection: "column",
    gap: "2.5rem",
    width: "100%",
  },
  chatQuestion: {
    alignSelf: "flex-end",
    backgroundColor: colors.muted,
    borderRadius: "1.5rem",
    maxWidth: "65%",
    paddingBlock: "0.625rem",
    paddingInline: "1rem",
    width: "fit-content",
  },
  code: {
    backgroundColor: colors.muted,
    borderRadius: "0.3em",
    fontFamily: "var(--typeset-mono)",
    fontSize: "0.85em",
    paddingBlock: "0.125em",
    paddingInline: "0.3em",
  },
  content: (fontFamily: string, fontSize: string, maxWidth: string) => ({
    fontFamily,
    fontSize,
    maxWidth,
  }),
  dd: {
    color: colors.mutedForeground,
    marginInlineStart: 0,
    marginTop: "0.25em",
    paddingInlineStart: "1em",
  },
  details: { marginBlockEnd: 0, marginBlockStart: "1.25em" },
  figcaption: {
    color: colors.mutedForeground,
    fontSize: "0.8125em",
    marginTop: "0.5em",
    textAlign: "center",
  },
  figure: { marginBlockEnd: 0, marginBlockStart: "1.25em", marginInline: 0 },
  firstChild: { marginBlockStart: 0 },
  fontScope: { display: "contents" },
  h1: {
    fontSize: "1.75em",
    fontWeight: 600,
    lineHeight: 1.3,
    marginBlockEnd: 0,
    marginBlockStart: "1.25em",
  },
  h2: {
    fontSize: "1.25em",
    fontWeight: 600,
    lineHeight: 1.4,
    marginBlockEnd: 0,
    marginBlockStart: "1.75em",
  },
  h3: {
    fontSize: "1.125em",
    fontWeight: 600,
    lineHeight: 1.45,
    marginBlockEnd: 0,
    marginBlockStart: "1.25em",
  },
  h4: {
    fontSize: "1em",
    fontWeight: 600,
    lineHeight: 1.5,
    marginBlockEnd: 0,
    marginBlockStart: "1.25em",
  },
  h5: {
    color: colors.mutedForeground,
    fontSize: "0.875em",
    fontWeight: 500,
    lineHeight: 1.5,
    marginBlockEnd: 0,
    marginBlockStart: "1.43em",
  },
  h6: {
    color: colors.mutedForeground,
    fontSize: "0.8125em",
    fontWeight: 500,
    letterSpacing: "0.08em",
    lineHeight: 1.5,
    marginBlockEnd: 0,
    marginBlockStart: "1.54em",
    textTransform: "uppercase",
  },
  heading: (fontFamily: string) => ({ fontFamily }),
  hr: {
    borderColor: colors.border,
    borderStyle: "solid",
    borderTopWidth: 1,
    borderWidth: 0,
    marginBlockEnd: 0,
    marginBlockStart: "2.5em",
  },
  image: { borderRadius: radius.lg, height: "auto", maxWidth: "100%" },
  inlineLink: {
    color: colors.foreground,
    fontWeight: 500,
    outlineColor: { ":focus-visible": colors.ring, default: "transparent" },
    outlineOffset: 2,
    outlineStyle: "solid",
    outlineWidth: { ":focus-visible": 2, default: 0 },
    textDecorationColor: {
      ":hover": "currentColor",
      default: "color-mix(in oklab, currentColor 30%, transparent)",
    },
    textDecorationLine: "underline",
  },
  list: {
    marginBlockEnd: 0,
    marginBlockStart: "1.25em",
    paddingInlineStart: "1.5em",
  },
  listItem: { marginTop: "0.5em", paddingInlineStart: "0.4em" },
  mark: {
    backgroundColor:
      "color-mix(in oklab, oklch(0.86 0.17 95) 40%, transparent)",
    borderRadius: "0.2em",
    color: "inherit",
    paddingBlock: "0.05em",
    paddingInline: "0.15em",
  },
  muted: { color: colors.mutedForeground },
  orderedList: { listStyleType: "decimal" },
  paragraph: { marginBlockEnd: 0, marginBlockStart: "1.25em" },
  pre: {
    backgroundColor: colors.muted,
    borderRadius: radius.lg,
    direction: "ltr",
    fontFamily: "var(--typeset-mono)",
    fontSize: "0.875em",
    lineHeight: 1.5,
    marginBlockEnd: 0,
    marginBlockStart: "1.43em",
    overflowX: "auto",
    paddingBlock: "0.75em",
    paddingInline: "1em",
    tabSize: 2,
  },
  preCode: {
    backgroundColor: "transparent",
    borderRadius: 0,
    fontFamily: "inherit",
    fontSize: "inherit",
    padding: 0,
  },
  previewPage: {
    backgroundColor: colors.background,
    color: colors.foreground,
    display: "flex",
    justifyContent: "center",
    minHeight: "100svh",
    paddingBlockEnd: { default: "6rem", "@media (min-width: 768px)": "8rem" },
    paddingInline: "1.5rem",
    paddingTop: { default: "2rem", "@media (min-width: 768px)": "6rem" },
  },
  root: (lineHeight: string, flow: string, monoFont: string) => ({
    "--typeset-flow": flow,
    "--typeset-mono": monoFont,
    lineHeight,
  }),
  section: { marginBlockEnd: 0, marginBlockStart: "1.25em" },
  strong: { fontWeight: 600 },
  summary: { cursor: "pointer", fontWeight: 500 },
  table: {
    borderCollapse: "collapse",
    fontSize: "0.875em",
    marginBlockEnd: 0,
    marginBlockStart: "1.43em",
    width: "100%",
  },
  tableCell: {
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    paddingBlock: "0.625em",
    paddingInline: "0.75em",
    textAlign: "start",
    verticalAlign: "top",
  },
  tableHead: { fontWeight: 600 },
  typeset: {
    color: colors.foreground,
    overflowWrap: "break-word",
    width: "100%",
  },
  unorderedList: { listStyleType: "disc" },
});
